### ISSUE TITLE
Search widget issue with search value/term

### ISSUE THREAD

**Issue by cwdotgis** [tmcgee/cmv-widgets#100]
I'm running into an issue with the Search Widget. The search function only works with some attributes and not others as the search term or value, even though it matches what's in my data. The unsuccessful search will draw the features on the map and zooms to the selection but the attribute table is not being populated with the results.

It seems to be happening with my polyline features and I can't figure out why. My search config file and the error messages I see in the Chrome developer console are here: https://gist.github.com/cwdotgis/00360da88b05ee33b7801ae264dc0074

**Comment by tmcgee** [comment]
Check that the features returned when the query is executed have valid geometries. This is best examined by running the query directly at the REST interface for the service.

**Comment by cwdotgis** [comment]
I am able to get results from directly querying the REST interface, with Return Geometry set to True:
![image](https://cloud.githubusercontent.com/assets/7365851/23529111/2b6dd832-ff51-11e6-913d-b8f98c36c1be.png). I can query for status='Pending' here but not in my CMV viewer with the search widget. It works fine with status='Going'

**Comment by tmcgee** [comment]
The fact that `status='Going'` works but `status='Pending'` does not further suggests there is some bad geometry in one of the 44 records. Perhaps a feature with a null geometry?

**Comment by cwdotgis** [comment]
I do see one record with shape = 0. I'll try to fix that and see what happens.

**Comment by tmcgee** [comment]
that would do it.

**Comment by cwdotgis** [comment]
Yes, that was it! Thank you, Tim.
