### ISSUE TITLE
LayerLabels

### ISSUE THREAD

**Issue by mtabdar** [tmcgee/cmv-widgets#106]
hi,
could you please provide an example to show how to use LayerLabels in an app? any specific configuration maybe?
thanks

**Comment by tmcgee** [comment]
@mtabdar,

Here is a basic configuration for the LayerLabels widget:

``` javascript
layerLabels: {
    include: true,
    type: 'invisible',
    path: 'widgets/LayerLabels',
    options: {
        map: true,
        layers: [
             {
                  id: 'supervisors', 
                  'labelExpressionInfo': {'value': '{SUP_DIST}'}
             }, 
             {
                  id: 'ugb',
                  'labelExpressionInfo': {'value': '{NAME}'}
             }
        ]
   }
}
```

**Comment by mtabdar** [comment]
Thanks for the response. I couldn't apply it. I was wondering if it is possible to add or remove labels on the fly and i found this
https://github.com/roemhildtg/cmv-widgets/tree/gh-pages/widgets/LabelLayer

**Comment by hohenstrater** [comment]
Hi, 
After some debugging and some other research I found out that one line of code was missing. One needs to include in the map options "showLabels : true". After that change, the labelling worked as expected.
