### ISSUE TITLE
Suggestion: automatically detect idProperty field if not provided

### ISSUE THREAD

**Issue by green3g** [tmcgee/cmv-widgets#11]
Would there be any disadvantage to having the attribute table widget automatically determine which ID field to use (if it's not provided) by looking for `esriFieldTypeOID`? It looks like the zoom to feature doesn't work correctly if no idProperty is provided.

**Comment by tmcgee** [comment]
Thanks. This is a good suggestion and will add this capability.

**Comment by tmcgee** [comment]
This has been added in commit [1d2568d](https://github.com/tmcgee/cmv-widgets/commit/1d2568deb451c41b772085972770d1f96f99203e)

**Comment by green3g** [comment]
Awesome, Thanks!
