### ISSUE TITLE
Popup windows are not showing when we use the fullscreen widget mode

### ISSUE THREAD

**Issue by mraminemx** [tmcgee/cmv-widgets#110]
Popup windows (layer submenu popups and basemaps popup) are not showing when we use the fullscreen mode of the fullscreen widget, there is a problem with the z-index of the popup and the position of popup div created outside the "borderContainerOuter" div

**Comment by tmcgee** [comment]
@mraminemx 

Thanks for pointing this out, It appears you can can fix this (at least for Chrome and Firefox) by including the following css:

``` css
.cmv .dijitPopup {
    z-index: 2147483647 !important;
}
```

2147483647 is the maximum value for z-index and what is used for fullscreen elements. http://stackoverflow.com/questions/18578244/displaying-elements-other-than-fullscreen-element-html5-fullscreen-api
