### ISSUE TITLE
Share Widget

### ISSUE THREAD

**Issue by MichelleJean28** [tmcgee/cmv-widgets#111]
Hi Tim,

Is it possible to integrate the Share Widget in any JavaScript 3.x web app or does it only work with the Configurable Map Viewer?
It looks like it should be a standard widget but I could not find any such reference or sample code in the ArcGIS API for JavaScript [website](https://developers.arcgis.com/javascript/3/jssamples/).

Sorry if my question sounds a little silly, I am quite new to coding.

Michelle

**Comment by tmcgee** [comment]
I doubt the Share widget would work in a JavaScript 3.x web app without modification. The concept was inspired by an old Esri template that was on github. I just did a quick search and could not find the original template.

**Comment by MichelleJean28** [comment]
A widget that shares ESRI products sounds kind of reasonable, too bad they don't have a sample code.
Thank you Tim !
