### ISSUE TITLE
Malformed Search Expression

### ISSUE THREAD

**Issue by cmccullough2** [tmcgee/cmv-widgets#112]
I am trying to allow upper & lower case text searches to work in the Search widget.  The rest services data is all caps, CELLVALUE. 

This expression works in my Flex app, upper(field_name) LIKE upper('%[value]%'); CELLVALUE.  I have tried many different combinations, but have not been able to get it to work.  Cellvalue.  Any thoughts.  I am assuming this is a simple fix.

**Comment by tmcgee** [comment]
It is very similar in javascript. This is taken from one of my apps:
``` javascript
expression: '(UPPER(Name) LIKE UPPER(\'%[value]%\'))',
```

**Comment by cmccullough2** [comment]
Thank you.   I knew I was overthinking it.
