### ISSUE TITLE
How to use LayerToggle

### ISSUE THREAD

**Issue by srinipalavalli** [tmcgee/cmv-widgets#118]
Hi,

Can anyone help me in how to use LayerToggle in CMV , or how to add Group Layers to CMV?

Thanks,
Srinivas

**Comment by tmcgee** [comment]
The LayerToggle widget is very simple to configure. You just provide the IDs for the layers you want to toggle between. Here is an example configuration:

``` javascript
layerToggle: {
    include: true,
    type: 'invisible',
    path: 'widgets/LayerToggle',
    options: {
        map: true,
        layerGroup: [
            'super',
            'ugb',
            'soi'
        ]
    }
},
```

**Comment by srinipalavalli** [comment]
Hi, Thanks for your reply and its working fine. How can I use two map services as a single group layer in CMV?

I want make two group layers and use LayerToggle for those two group layers

**Comment by srinipalavalli** [comment]
Can anyone please help me on the above query?.

**Comment by tmcgee** [comment]
Grouping layers in the CMV layerControl widget is not supported at this time.

**Comment by srinipalavalli** [comment]
Ok. Thanks for the quick response.
