### ISSUE TITLE
Search widget buffer sizing

### ISSUE THREAD

**Issue by tr3vorm** [tmcgee/cmv-widgets#119]
I have had someone report a problem with the buffer sizes when searching by shape. I can reproduce the problem by following these steps. 
1. Search an attribute by shape
2. Draw a shape (e.g. a point.
3. Set the buffer to e.g. 100m
4. Use the measure tool to check the buffer size (it is correct). 
5. Click the search button
6. The buffer shrinks to ~77m and only includes results within the 77m 

Subsequent changes to the search shape get drawn correctly, but then it is changed when performing the search. I am wondering if this problem has appeared before, or is it specific to our configuration?

**Comment by tr3vorm** [comment]
I am working through the code as I noticed that the search widget is out of date. Will report back when I have the new code working.

**Comment by tr3vorm** [comment]
After updating the widget code (Search and Attribute Table) to the current code, the buffer size error is no more.  I still have another error related to infoTemplates (assume its my config) but will open another issue if I cannot resolve it.

**Comment by tmcgee** [comment]
The error related to `infoTemplates` is a new addition and something I am in the middle of working on. This is the fix for line 366 of Search.js:

``` javascript
infoTemplates: lang.clone(search.infoTemplates || layer.infoTemplates || {})
```

**Comment by tr3vorm** [comment]
Many thanks! I was struggling `infoTemplates` in the search config. 

One minor bug I see is that the attribute table has it's headings overwritten with the results if there is a `FindTask()` instead of a `QueryTask()` in the search widget config. I can create a new issue as I doubt it is related to anything here.

**Comment by tmcgee** [comment]
@tr3vorm I have commited/pushed the fix for infoTemplates to this repo.

I see what you are referring to regarding FindTask though do not have  an immediate fix. Please create another issue so we can track this separately.

**Comment by tmcgee** [comment]
@tr3vorm issue with FindTask fixed in https://github.com/tmcgee/cmv-widgets/commit/d565619de240f42a8fbac5671644cd0b53b4ffb8
