### ISSUE TITLE
Legend as a domNode on Map

### ISSUE THREAD

**Issue by srinipalavalli** [tmcgee/cmv-widgets#121]
Hi, Can I use legend as a domNode on the map instead of loading in the left pane?

**Comment by tmcgee** [comment]
Yes, you can use the legend widget as a `type: 'domNode'`. As I simple demonstration, I did this:

``` javascript
legend: {
    include: true,
    id: 'legend',
    type: 'domNode',
    srcNodeRef: 'growlerDijit',
    path: 'gis/dijit/Legend',
    title: i18n.viewer.widgets.legend,
    iconClass: 'fa-picture-o',
    open: false,
    position: 1,
    options: {
        map: true,
        style: 'background-color:#FFF;padding:10px;border:1px solid #333;',
        legendLayerInfos: true
    }
},
```

![image](https://cloud.githubusercontent.com/assets/200780/26658489/41d722da-461f-11e7-8dd6-a2ae1c5dd017.png)


This uses the `growlerDijit` dom node intended for the `growler` widget so not something I would do in an application. Hopefully it gives you some direction for how you might want to do this in your own application..

**Comment by srinipalavalli** [comment]
That's cool. Thanks Tim.
