### ISSUE TITLE
FullScreen widget

### ISSUE THREAD

**Issue by Samaalir** [tmcgee/cmv-widgets#123]
Hi, does anyone know how to use at the same time the homeButton and Full screen button ?, where I must create a button so that it will be beside the home/locate buttons

**Comment by tmcgee** [comment]
@Samaalir You have a couple of options:

1. If you are not using the locateButton widget, you can use `srcNodeRef: ['locateButton'`]` https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/templates/mapOverlay.html#L16

2. or add another div tag at that same place in the template with a unique id like `fullScreenButton` and use that Dom node.
