### ISSUE TITLE
Using identify widget to show related records

### ISSUE THREAD

**Issue by Samaalir** [tmcgee/cmv-widgets#125]
how can I display some values in the popup menu 

i tried to use 

```
{
                        fieldName: 'relationships/1/nom_commune',
                        label: 'Nom Commune',
                        visible: true
                    },
```
when I check Network in the Google inspector, I found the request have been executed

`{"objectIdFieldName":"OBJECTID","globalIdFieldName":"","fields":[{"name":"nom_commune","alias":"nom_commune","type":"esriFieldTypeString","length":1073741822}],"features":[{"attributes":{"nom_commune":"Oulad Imloul"}}]}`

but it seem like I am missing something, and in the popup i can see just the label and not the record

**Comment by tmcgee** [comment]
@Samaalir For related records, your best bet is to use the [RelationshipTable widget](https://github.com/roemhildtg/cmv-widgets/tree/master/widgets/RelationshipTable) from @roemhildtg
