### ISSUE TITLE
Search Widget: Functionality

### ISSUE THREAD

**Issue by drusexton** [tmcgee/cmv-widgets#128]
@tmcgee Following up on my question from Search Widget #3 I am attempting to determine if/and how you can exclude a layer from the Search by Attributes tab, but still show it in the Search by Shape tab. The image below should sort of help depict what I mean.

![cmv search](https://user-images.githubusercontent.com/14102180/28177945-aadd1894-67ca-11e7-9a83-6c71f82c97e7.jpg)

You can also hit the [Public URL](http://bhgis.org/apeg/woodproducts/dev) if you're interested.

Second I am curious to know how you can go about having the bottom pane closed upon opening the application. I tried to go and change the following code in the viewer.js to reflect the following change open: false as shown in the code below:

`panes: {
        bottom: {
         	id: 'sidebarBottom',
        	placeAt: 'outer',
        	splitter: true,
        	collapsible: true,
        	region: 'bottom',
                open: false,
                style: 'height:200px;',
                content: '<div id="attributesContainer"></div>'
         }
}`

Is there some other location that I need to change this function?

**Comment by drusexton** [comment]
For anyone wondering I was able to look back over the config/Search.js file that comes with the master widget files. I noticed you cannot change the following: open: false; you must use open: 'none' as indicated in the notes.

`bottom: {
         	id: 'sidebarBottom',
        	placeAt: 'outer',
        	splitter: true,
        	collapsible: true,
        	region: 'bottom',
                open: 'none',
                style: 'height:200px;',
                content: '<div id="attributesContainer"></div>'
}`

**Comment by tmcgee** [comment]
@drusexton Thanks. This new issue helps clarify your objective. For the first part, currently there is no way to exclude a layer from the `By Attribute` tab. You can already exclude from the `By Shape` tab so this is a good addition.

I am testing a very simple enhancement to the widget that would accomplish this. Hopefully I will have that added to the repo in the next day or so.

**Comment by drusexton** [comment]
@tmcgee have you made an progress on the enhancement?

**Comment by tmcgee** [comment]
@drusexton I did complete this soon after my last post. With the current version, If you have no attribute searches configured for a layer, that layer will not  appear in the `By Attribute` tab.

**Comment by drusexton** [comment]
@tmcgee I apologize for being such a newbie but am not sure I follow... I understand I need to have no attribute searches configured on the layer, but I am not sure where to implement this.

**Comment by drusexton** [comment]
@tmcgee I went back to the original files because I changed the original parameters, and I was getting lost. Anyhow I went back and commented out the attributes section and this omitted the layer which is included in the By Shape search, from the By Attribute search. However whenever I attempt to run a search By Shape, there is no result. I check the console and I am not sure how to fix the issue (init.js.174) which seems to be on the font draw icon? Here is the [PU](http://bhgis.org/apeg/woodproducts/dev/cmv-widgets-master/demo.html?config=search), and below is my code:

```
{
                name: 'All Suppliers',
                expression: '', // additional where expression applied to all queries
                idProperty: 'objectid',
                labelWidth: 110,
                queryParameters: {
                    type: 'spatial', // spatial, relationship, table or database
                    layerID: 'apegWoodProducts', // from operational layers
                    sublayerID: 0,
                    outFields: ['*']
                },
                infoTemplates: {
                    buffer: {
                        title: 'Search Buffer',
                        content: function (feature) {
                            if (feature.geometry) {
                                return number.format(geometryEngine.geodesicArea(feature.geometry, 'acres'), {
                                    places: 2
                                }) + ' Acres';
                            }
                            return '';
                        }
                    }
                }/*,
                attributeSearches: [
                    {
                        name: 'Search For Assessments',
                        searchFields: [
                            {
                                field: 'Inspector Name',
                                label: 'Inspector Name',
                                expression: '(inspector LIKE \'[value]%\')',
                                width: 'calc(100% - 130px)'
                            },
                            {
                                field: 'Type of Damage',
                                label: 'Type of Damage',
                                expression: '(typdamage LIKE \'[value]%\')',
                                values: ['*', 'Destroyed', 'Major', 'Minor'],
                                width: 125
                            }
                        ],
                        title: 'Company Search Results',
                        topicID: 'companySearch',
                        gridOptions: {
                            columns: [
                                {
                                    field: 'CompanyName',
									label: 'Company Name',
									sortable: true,
									resizable: false,
									width: 150
                                },
                                {
                                    field: 'FullAddress',
                                    label: 'Address',
                                    sortable: false,
									resizable: true
                                },
                                {
                                    field: 'PhoneNumber',
                                    label: 'Phone Number',
                                    sortable: false,
									resizable: true
                                },
                                {
                                    field: 'ContactName',
                                    label: 'Contact',
                                    sortable: false,
									resizable: true
                                },
								{
                                    field: 'SecondaryCategory',
                                    label: 'Main Industry Sector',
                                    sortable: true,
									resizable: true
                                },
								{
                                    field: 'DescriptiveSummary',
                                    label: 'Descriptive Summary',
                                    sortable: false,
									resizable: true
                                }
                            ],
                            sort: [
                                {
                                    attribute: 'CompanyName',
                                    descending: false
                                }
                            ]
                        }
                    }
                ]*/
            },                               
```

**Comment by drusexton** [comment]
@tmcgee Thanks for your assistance.
