### ISSUE TITLE
Can't Export in IE9 or 10 or 11?

### ISSUE THREAD

**Issue by JurupaCommunity** [tmcgee/cmv-widgets#13]
Hi,
Export widget is not working in IE? Is there possible fix to this? (There is a note that it not working for IE 9 or older but i try 10 and 11 and it not working as well. Is there a setting in IE i need to do? ) 

Thanks,

![capture](https://cloud.githubusercontent.com/assets/11335138/7497035/e301f894-f3cc-11e4-9a30-e115af47c6e3.JPG)

**Comment by tmcgee** [comment]
The export has been tested and works with both IE 10 and IE 11 in multiple environments. The only thing I can think of is to check the setttings in the browser, web page and web server to ensure that the browser is not froced into compatibility mode to emulate older versions of IE.

**Comment by JurupaCommunity** [comment]
Hi Tim,

I try your http://tmcgee.github.io/cmv-widgets/demo.html?config=table on my computer which is IE 9, it not working. My gis server with IE 10 or my other server with IE 11 and a laptop with IE 10 and it not export. I turn Block Popup off, no compatibility mode and it still not working. Is there special addon or something you have that I might not?

Thanks,

ANh

**Comment by green3g** [comment]
I'm also experiencing this, I'm running IE 11. Clicking the export button appears to fails silently as well, so there's no errors in the console. The export works well in Chrome and Firefox. 

Just double checked Compat mode, and it is turned off. The meta tag is set: 
`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by JurupaCommunity** [comment]
Hi Gregg,
Do you get it to export in IE? 
I used mediaInfos in the Identify to pull up the URL to the pdf record drawing and it open up fine in IE but in Firefox/chrome, it open up site address + the URL link ( \main....)  example: (http://gis02/sewer/fieldeditting/\main\public\Record Retention\Record Drawings\Tracts\TR - 2002352829.pdf). Therefore if i get the export work in IE then everything work in one browser. Thanks,

**Comment by tmcgee** [comment]
I suspect that there may have been a subsequent Windows Update that broke this in IE 10 and IE 11. This used to work for me in both IE 10 and 11 but does not any longer with no changes to the underlying export code. My reasoning for suspecting Windows update is that this still works for my client using IE 10 whom I originally implemented the export. Not surrprising as there is typically a substantial delay while their IT group tests Windows Updates before rolling them out to the masses. If that breaks for them sometime in the future, I may be tasked with coding a fix.

**Comment by tmcgee** [comment]
The latest version offers a new approach to exporting Excel/CSV that seems to work with IE 11. I have not yet tested with IE 10. Please try it and let me know how it goes.

**Comment by gobsmack** [comment]
I just tested the Export Widget in a Win7 IE10 virtual machine, and it works. So, I think the issue can be closed.

**Comment by tmcgee** [comment]
thanks @gobsmack
