### ISSUE TITLE
Search Widget: app.js issue & resolution

### ISSUE THREAD

**Issue by drusexton** [tmcgee/cmv-widgets#132]
@tmcgee I have been working to implement the Search widget, and was continuing to have no success. However when I would try to implement it in the widget "test" environment (http://bhgis.org/apeg/dev/cmv-widgets-master/demo.html?config=disclaimer) it was working great. Yet when I included the same config files, and  implemented the exact same code in my application I kept getting a few odd error message from the console: 

init.js:35 GET http://js.arcgis.com/3.20compact/jquery.js  

init.js:36 Error: scriptError at f (init.js:10) at HTMLScriptElement.<anonymous> (init.js:35)

I really do not understand there errors, so I began to compare code from the config files and everyone thing seemed to match. So I started to ask myself what files exist in the widgets-master folder that are not included in my folders. Upon comparing the code for my config files app.js stood out to me.  When I opened them up side by side I noticed an immediate line of code that was missing from my existing app.js config:

```
// jquery is only required for the Advanced Search in Search widget
            {
                name: 'jquery',
                location: '//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1',
                main: 'jquery.min'
            }
// end jquery
```
After adding this line to my app.js config file like so:

```
(function () {
    var path = location.pathname.replace(/[^\/]+$/, '');
    window.dojoConfig = {
        async: true,
        packages: [
            {
                name: 'viewer',
                location: path + 'js/viewer'
            }, {
                name: 'gis',
                location: path + 'js/gis'
            }, {
                name: 'config',
                location: path + 'js/config'
            }, {
                name: 'proj4js',
                location: '//cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15'
            }, {
                name: 'flag-icon-css',
                location: '//cdnjs.cloudflare.com/ajax/libs/flag-icon-css/2.8.0'
            },
			// jquery is only required for the Advanced Search in Search widget
            {
                name: 'jquery',
                location: '//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1',
                main: 'jquery.min'
            }
            // end jquery
        ]
    };
```

The issue was resolved and the search seems to work as I expected. I hope this helps if anyone else comes across this issue...

**Comment by durga-pericherla** [comment]
Hai @drusexton I am trying to add search widget in my Viewer. I have done the modification you mentioned above in the app.js file but still search widget is not loading in the Viewer and I got the following error in the console.

Loading failed for the <script> with source “file:///ajax/libs/jquery/3.2.1/jquery.min.js”. index.html:1
Error: "scriptError"
ghttps://js.arcgis.com/3.21compact/:10:382hhttps://js.arcgis.com/3.21compact/:35:210 3.21compact:36:495
<anonymous>
https://js.arcgis.com/3.21compact/:36:495
m.signal/<
https://js.arcgis.com/3.21compact/:14:447
a
https://js.arcgis.com/3.21compact/:10:295
m.signal
https://js.arcgis.com/3.21compact/:14:419
m.injectUrl/h<
https://js.arcgis.com/3.21compact/:35:200
src: dojoLoader 3.21compact:37:36
info: 
(2) […]
​
0: "//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
​
1: error { target: script, isTrusted: true, srcElement: script, … }
​
length: 2
​
<prototype>: Array []
3.21compact:37:36
. 3.21compact:37:60

**Comment by tmcgee** [comment]
@ParkShinYoo Since you error shows `file:///`, that tells me you are not using a web server but accessing the cmv application from your file system.  While not required, a web server is best for development of your cmv application, even if it is a simple python script or nodejs.

If you want to continue using the file system, you need to add `https://` at the start of the url for JQuery/Proj4JS/etc instead of simply `//`. That may not resolve all issues you encounter but is a minimal requirement.

**Comment by durga-pericherla** [comment]
@tmcgee thank you, after adding https:// its working now. I will use the web server for accessing the CMV application thanks for the suggestion.
