### ISSUE TITLE
Search Widget: 404 Error draw-icons.woff

### ISSUE THREAD

**Issue by drusexton** [tmcgee/cmv-widgets#134]
@tmcgee I was able to get the widget to work for me. Despite the fact that the widget seems to function as expected I kept getting an odd error message: 404 Error on draw-icons.woff. It bothered me and so I decided to look for the .woff file that appeared to either be missing, however the file did indeed exist. Next I thought there has to be reference issue. I did a little research on error 404 draw-icons.woff and learned that it was a .css referenceing issue. I went into the widget folder Search/css/ and I examined the Draw.css file. It was here that I discovered a referencing issue:

```
@font-face {
    font-family: "draw-icons";
    font-style: normal;
    font-weight: normal;
    src:url("./fonts/draw-icons.eot");
    src:url("./fonts/draw-icons.eot?#iefix") format("embedded-opentype"),
    url("./fonts/draw-icons.woff") format("woff"),
    url("./fonts/draw-icons.ttf") format("truetype"),
    url("./fonts/draw-icons.svg#draw-icons") format("svg");
}
```

It appeared the file was not being properly referenced. So I simply added css to the code as show below:

```
@font-face {
    font-family: "draw-icons";
    font-style: normal;
    font-weight: normal;
    src:url(".css/fonts/draw-icons.eot");
    src:url(".css/fonts/draw-icons.eot?#iefix") format("embedded-opentype"),
    url(".css/fonts/draw-icons.woff") format("woff"),
    url(".css/fonts/draw-icons.ttf") format("truetype"),
    url(".css/fonts/draw-icons.svg#draw-icons") format("svg");
}
```
The application behavior does not seemed to have changed aside from the fact there is no 404 error on draw-icons.woff.

**Comment by tmcgee** [comment]
@drusexton The reference to the fonts was correct originally - it should be relative to the css folder as `./fonts...`.

The error you see in the console most likely results from a missing configuration for the WOFF mime-type on the server. Optional configuration since the font files can be referenced in many ways due to differences in browsers. The multiple lines within the font css are there to handle those variations.

As you said, this doesn't affect the widget. I'd recommend you remove you customization to avoid confusion with future updates.

**Comment by drusexton** [comment]
@tmcgee just for clarification so I understand, what you are telling me that the following error shouldn't be an issue:

downloadable font: download failed (font-family: "draw-icons" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://bhgis.org/apeg/woodproducts/js/gis/dijit/Search/css/.css/fonts/draw-icons.ttf - draw.css:3:12

So I would be better to remove the customization in an effort to avoid confusion later on?

**Comment by tmcgee** [comment]
That is correct.
