### ISSUE TITLE
Attribute doesnt display properly in bottom pane after setting property open:false in panes bottom

### ISSUE THREAD

**Issue by mayur9785** [tmcgee/cmv-widgets#135]
Hi,
I have added the AttributeTable widgets. placing it in the bottom pane of app as is recommended. Now, If I add open:false in panes configuration, Attribute tables not displaying in the proper bottom area, instead it is display in left corner of the bottom pane. If you don't add this property open:false, it is display properly in bottom area. I am attaching both the screenshots below

if open:false in bottom panes property and click on collapse button and open it display as below

![1](https://user-images.githubusercontent.com/6058868/29327403-ac8254f6-81f7-11e7-9df9-dfb5c377bd50.PNG)

without open:false property

![2](https://user-images.githubusercontent.com/6058868/29327415-b2c8c5a2-81f7-11e7-997a-c706ce422924.PNG)

**Comment by tmcgee** [comment]
Did you try `open: 'none'`? Note the comment [here](https://github.com/tmcgee/cmv-widgets/blob/master/config/search.js#L39) that false does not work.

**Comment by mayur9785** [comment]
@tmcgee many thanks 👍  perfect.
