### ISSUE TITLE
How to open Attribute table from Sublayer menu of dynamic layers

### ISSUE THREAD

**Issue by mayur9785** [tmcgee/cmv-widgets#136]
I added this in LayerControl widgets options
```
subLayerMenu: {
                        dynamic: [{
                            label: 'Open Attribute Table',
                            topic: 'openTable',
                            iconClass: 'fa fa-table fa-fw'
                        }]
                    }
```
I am getting Open Attribute Table menu option but, by clicking on that menu Attribute Table doesn't display. What are the additional steps are required to open the Attribute Table from sub layer menu.

I seen the related issue here tmcgee/cmv-widgets#21.

I added code in viewer.js file

Now here is the OpenAttributeTable Code after topic.subscribe('layerControl/goodbye', function (event) {...
```
topic.subscribe('LayerControl/openAttributeTable', function (r) {
        var data_list = [
            {
                title: 'AttributesTable',
                topicID: 'AttributesTable',
                queryOptions: {
                    queryParameters: {
                        url: r.layer.url + '/' + r.subLayer.id,
                        maxAllowableOffset: 100,
                        where: '1=1'
                    },
                    idProperty: 'ObjectID'
                }
            }
        ];
        console.log(data_list);
        //this.addTables(data_list);
        //this.tables = data_list;
        topic.publish('attributesContainer/addTables', data_list);
    });
```
Attributetable is not opening with above code

**Comment by tmcgee** [comment]
@mayur9785 In your first code snippet, you are using `openTable`. In the second code snipper, you are using `openAttributeTable`. Those 2 need to be the same. You can set break-points in your code within Chrome DevTools to ensure that each snippet is executing.

**Comment by mayur9785** [comment]
@tmcgee many thanks. I changed and it is executing 👍

**Comment by adityakumar529** [comment]
@mayur9785 @tmcgee I tried the same but in my case I am just getting a array with no values.
![image](https://user-images.githubusercontent.com/17431182/35224532-4dc9d164-ffab-11e7-818c-c3ed19991a8d.png)
On the other hand if I go with the layer query using rest API, I am getting values.

**Comment by tmcgee** [comment]
@adityakumar529 You should look at the resulting request to the REST API in Chrome Dev Tools. If you open that query request in a browser, you hopefully can determine what parameters need adjustment in order to return values.

**Comment by adityakumar529** [comment]
From where are we getting   topic.publish('attributesContainer/addTables', data_list)?
For Growler I can find a JS file in Dijit but for attributesContainer there is nothing similar.Do we need to have a JS for attribute container as well?

**Comment by tmcgee** [comment]
@adityakumar529 I assume you are using my AttributesTables widget in this repo:
https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable.js#L38
https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable.js#L92

**Comment by adityakumar529** [comment]
Yes, I am using the same. Have added AttributeTable related files. 
This is the way I am calling the widget.

		attributesTable: {
    include: true,
    id: 'attributesContainer',
    type: 'domNode',
    srcNodeRef: 'attributesContainer',
    path: 'gis/dijit/AttributesTable',
    options: {
        map: true,
        mapClickMode: true,
        useTabs: false,
        sidebarID: 'sidebarBottom'
    }
},
and sublayer option:
 subLayerMenu: {
					
                        dynamic: [
  {
      topic: 'goodbye',
       iconClass: 'fa fa-frown-o',
      label: 'Say goodbye'
  }, {
      label: 'AttributesTable',
      topic: 'AttributesTable',
      iconClass: 'fa fa-table fa-fw'
  }]
                    }

	 topic.subscribe('layerControl/AttributesTable', function (r) {
	
		   var data_list = [ 
                { 
                    title: 'AttributesTable', 
                    topicID: 'AttributesTable',
                    queryOptions: {
                        queryParameters: {
                            url: r.layer.url + '/' + r.subLayer.id,
                            maxAllowableOffset: 100,
                            where: '1=1'
                        },
                        //idProperty: 'ObjectID'
                    }
                } 
            ]; 
		
	 console.log(data_list);
        topic.publish('attributesContainer/addTables', data_list)
		
    });

I think I am not able to enable the widget.

**Comment by tmcgee** [comment]
@adityakumar529 A few questions to help you troubleshoot your implementation:

* Do you have a [bottom pane](https://github.com/tmcgee/cmv-widgets/blob/master/config/table.js#L24-L32)?
* Do you see the AttributesTable files loaded in Chrome Dv Tools sources tab?
* Are there any related error messages in the Chrome Dev Tools console?
* Do you see query requests sent to the REST end-point in the Chrome Dev Tools network tab?
