### ISSUE TITLE
Search with related tables

### ISSUE THREAD

**Issue by JulianInskip** [tmcgee/cmv-widgets#14]
Hi Tim. I am trying to get your Search widget with related tables working. I managed to get the search working with my properties dynamic layer and it opens the table. I also have setup the relationship part of it (using your -relatedRecords.js). It opens the related table, however, it returns the incorrect entries according to how the relationship is setup. It then also zooms to a totally difference feature when I click on the related table record (the related table has no shape).

Do I need to setup anything specifically in the relationship part of the code or is everything handled in the relationship in the service?

These are MXD relates and not GDB relationship classes (if that makes a difference).

I should have this on our test server if you need to check it out.

Thanks.

**Comment by JulianInskip** [comment]
Below is a sample of my relate section. A few questions of this if I may:
- what is the `id: '...',` for?
- what is the `topicID: '...',` for?
- what is the `idProperty: 'OBJECTID'` for?

The relate is from a property feature class ("SGCODE" field) to a debtors table ("GIS_LINK" field)

```
///////////////////////////////////////////////////////
// Code sample
///////////////////////////////////////////////////////
{
    id: 'Active Debtors',
    field: 'OBJECTID',
    label: 'Active Debtors',
    width: 100,
    sortable: false,
    exportable: true,
    renderCell: function (object, value, node) {
        on(node, 'click', function () {
            topic.publish('attributesContainer/addTable', {
                title: 'Relate - Active Debtors',
                topicID: 'relatedActiveDebtorsQuery',
                queryOptions: {
                    queryParameters: {
                        type: 'relationship',
                        layerID: 'admbilling',
                        sublayerID: 1,
                        relationshipID: 0,
                        objectIDs: [value],
                        outFields: ['*']
                    },
                    idProperty: 'OBJECTID'
                },
                featureOptions: {
                    selected: false
                },
                toolbarOptions: {
                    show: false
                },
                gridOptions: {
                    columns: [
                        {
                            field: 'OBJECTID',
                            label: 'OBJECTID',
                            width: 20
                        },
                        ...
```

**Comment by tmcgee** [comment]
@JulianInskip I am now returned from an extended vacation. Did you get this resolved?

**Comment by JulianInskip** [comment]
@tmcgee Welcome back, hope you had a good break. I did manage to get it right, thanks very much. I can't remember exactly 100% what I did to correct it, but it was something to do with an incorrect field/sublayerID/relationshipID that I was using. It works really well now, thanks for getting back to me.

**Comment by tmcgee** [comment]
great to hear!

**Comment by carrbrpoa** [comment]
Is it possible to search by an attribute of related table?
Example:
Assume you have VEHICLE and CARGO tables - N CARGO records for 1 VEHICLE - and you want to search for VEHICLES with CARGO.TYPE = 'XYZ'. Considering you want to input this CARGO.TYPE and maybe other VEHICLE fields in search widget to query for records of VEHICLES with these characteristics, how could you build the search config?

**Comment by tmcgee** [comment]
I do not have a way to do this at present. As a possible work-around, you can create a spatial join between the feature class and the table and publish that in your map service. Then you can query on all fields within that published layer. I don't know if that is possible within your environment.

**Comment by carrbrpoa** [comment]
Hmmm...it is possible, but somehow I don't like this approach, seems too denormalized to me. What do you think about maybe an improvement in Search widget that make some kind of _two steps search_ (search relates and then search it's parent to show results), with some flag in config that indicates you wish to do it? :D
I volunteer myself as soon as I find some free time!
