### ISSUE TITLE
Problem with Disclaimer? CMV 2.0.0-Beta2

### ISSUE THREAD

**Issue by gisnovice** [tmcgee/cmv-widgets#141]
Hi, I am trying to use the disclaimer widget.

I just downloaded the files.

I dropped the widget into 'js/gis/dijit' folder, and changed my path accordingly.. path: 'gis/dijit/Disclaimer',

`        widgets: {
            disclaimer: {
                include: true,
                id: 'disclaimer',
                type: 'floating',
                path: 'gis/dijit/Disclaimer',
                title: 'Disclaimer',
                options: {

                    // pre-define the height so the dialog is centered properly
                    style: 'height:295px;width:375px;',

                    // or you can provide the url for another page that includes the content
                    href: './disclaimer.html'

                }
            },`

It is not showing up for me with the new CMV. Do i need to change anything else?

**Comment by tmcgee** [comment]
@gisnovice To use the disclaimer and other widgets that need open without any user interaction, you can use `preload: true` as show in the [example configuration](https://github.com/tmcgee/cmv-widgets/blob/master/config/disclaimer.js#L35)

**Comment by gisnovice** [comment]
@tmcgee solved this issue with "preload: true,"
