### ISSUE TITLE
Attribute Table - Zoom in to feature on row click

### ISSUE THREAD

**Issue by mayur9785** [tmcgee/cmv-widgets#142]
Hi,

I have below issues 

- Clicking on attribute table rows, it is not zoom in to the features. I checked I am passing the correct idProperty.

- Zoom button (next to clear button) is missing in attributeTable toolbar.

- I set the open:'none' in panes bottom configuration to not to show by default it is fine but, after adding query options it shows the bottom pane open, I want to set open:'none' even after query options and not to show attributeTable open untill you click on expand button

There is no error in console 

below is the configuration

panes configuration 
`
bottom: {
         	id: 'sidebarBottom',
         	placeAt: 'outer',
         	splitter: true,
         	collapsible: true,
         	open: 'none',
         	region: 'bottom',
         	style: 'height:250px;',
         	content: '<div id="attributesContainer"></div>'
        }
`

widget configuration 
`
attributesTable: {
                include: true,
                //open: 'none', 
               //open: false, 
                id: 'attributesContainer',
                type: 'domNode',
                srcNodeRef: 'attributesContainer',
                path: 'gis/dijit/AttributesTable',
                options: 'config/attributesTable'
            }

`
Config file attributesTable 

`
define({
    map: true,
    mapClickMode: true,
    useTabs: true,
    sidebarID: 'sidebarBottom',

    /*
        any predefined tables to add to the tab container or possibly just one table
    */
    tables: [
        {
            // title for tab
            title: 'Road Safety',

            // unique topicID so it doesn't collide with
            // other instances of attributes table
            topicID: 'auditStageQuery',

            // allow tabs to be closed
            // confirm tab closure
            closable: false,
            confirmClose: true,

            queryOptions: {
                // parameters for the query
                queryParameters: {
                    url: 'http://myserver/arcgis/rest/services/Road_AS/MapServer/0',
                    maxAllowableOffset: 100,
                    where: '1=1',
                },
                idProperty: 'ObjectID'
            },
            featureOptions: {
                /*
                    Show the resulting features on the map
                */
                features: false,

                /*
                    Allow records to be selected in the grid
                */
                selected: true,

                /*
                    Allow the display of an info window when a feature is selected
                */
                infoWindow: true,

                /*
                    Allow the user to highlight features that have been selected in the grid
                */
                highlight: true,

                /*
                    Show the source feature used in the search
                */
                source: true,

                /*
                    Allow the creation and display of a buffer
                */
                buffer: true,

                /*
                    Do we zoom to the source features after the query
                */
                zoomToSource: true,

                /*
                    Do we zoom to the selected features after the query
                */
                zoomToSelected: true,

                /*
                    Allow StreetView when there is a single selected feature
                */
                streetView: false
            }
        }
    ],
});
`

**Comment by tmcgee** [comment]
`features: false,` <- this must be set to true. If there are no features on the map, there is nothing to zoom to.

If you don't want to see the features but still need them to zoom to, set a transparent symbol for rendering. The symbolOptions below cover point/line/polygon:

``` javascript
symbolOptions: {
    features: {
        point: {
            type: 'esriSMS',
            style: 'esriSMSCircle',
            size: 15,
            color: [200, 0, 200, 0],
            angle: 0,
            xoffset: 0,
            yoffset: 0,
            outline: {
                type: 'esriSLS',
                style: 'esriSLSSolid',
                color: [200, 0, 200, 0],
                width: 2
            }
        },
        polyline: {
            type: 'esriSLS',
            style: 'esriSLSSolid',
            color: [200, 0, 200, 0],
            width: 2
        },
        polygon: {
            type: 'esriSFS',
            style: 'esriSFSSolid',
            color: [255, 0, 255, 0],
            outline: {
                type: 'esriSLS',
                style: 'esriSLSSolid',
                color: [200, 0, 200, 0],
                width: 1
            }
        }
    },
},
```

**Comment by mayur9785** [comment]
@tmcgee Thank you very much for your reply. I changed the feature : true and it is highlighting the features on map.

I have one more issue now,when application open All features highlighted on map but, map zoom in to the other region by default, If you see the coordinates info lower left corner mapinfo it shows "Nan".
After debug, I see the error in _GraphicsMixin.js file > getGraphicsExtent function > at this line
`
zoomExtent = graphicsUtils.graphicsExtent(layer.graphics); // Its null here
`
I am using ESRI basemap and my dynamiclayer spatial reference is 2932

Do I need to change spatialreference property in any widgets config or .js file ?

Could you please suggest me on this What I am missing ?

Many Thanks :)

**Comment by tmcgee** [comment]
@mayur9785 The REST API converts the results of the QueryTask to the spatial reference of your map - presumably web mercator in your case because of the Esri basemap.

While there isn't an image attached to "see" the "NaN" coordinates, I don't think this would be related to the query in any way.

The line you reference is using a method in the Esri JavaScript API to get the extent of the graphics in the layer so I'm not completely familiar with the exact code in that method. If it is coming back null, I wonder if there is are some invalid features being returned from the query.  If you change your query to include just one feature or a few features that you are certain have valid geometry, does it still return null?

**Comment by mayur9785** [comment]
@tmcgee Yes you are correct. If I change query for just single feature or few features it doesn't return null and it's works perfect. 

When query return invalid geometry, coordinates shows "Nan" and getting below error in console. 

**svg.js:43 Error: <circle> attribute cx: Expected length, "NaN".
setShape @ svg.js:43**

**Error: <circle> attribute cy: Expected length, "NaN".
setShape @ svg.js:43**

Many thanks for your help 👍 :)

**Comment by mayur9785** [comment]
@tmcgee I want to highlight features and zoom in only when I click on attribute table grid row.

I set below parameters in attributeTable config.js file
```
symbolOptions: {
    features: {
   // Here I set transparent symbols as I don't want to highlight features by default on map but still need 
    them to zoom to
  // this is fine and features are not highlighted on map and zoom In works
  },
   highlighted: {
   // Here I set transparent symbols as I don't want to highlight features on mouseover 
  // this is fine and feature is not highlighted on mouseover 
  }
}
```
Now, when I click on feature it is still highlighting the feature on map with identify popup information

I click 2nd , 3rd feature and so on ...the previous features are not cleared. look at the image below

![capture](https://user-images.githubusercontent.com/6058868/29864444-6d6e1356-8d7b-11e7-99de-01ece65904ac.PNG)

If i do clear all features from clear menu and click on features its fine

I want to highlight features and zoom in only when I click on attribute table grid row. I tried selected:false, but when you click on grid row it is zoom in to features and not selected. 

below is featureoptions

```
featureOptions: {
                /*
                    Show the resulting features on the map
                */
                features: true,

                /*
                    Allow records to be selected in the grid
                */
                selected: true,

                /*
                    Allow the display of an info window when a feature is selected
                */
                infoWindow: false,

                /*
                    Allow the user to highlight features that have been selected in the grid
                */
                highlight: true,

                /*
                    Show the source feature used in the search
                */
                source: false,

                /*
                    Allow the creation and display of a buffer
                */
                buffer: false,

                /*
                    Do we zoom to the source features after the query
                */
                zoomToSource: false,

                /*
                    Do we zoom to the selected features after the query
                */
                zoomToSelected: true,

                /*
                    Allow StreetView when there is a single selected feature
                */
                streetView: false
            },
```

**Comment by tmcgee** [comment]
@mayur9785 From your screenshot, it appears to be identifying a map layer, not the features in the AttributesTable. Perhaps I am forgetting about some functionality I wrote awhile ago but I don;t think you can identify 6 features at once from the AttributesTable rows.
