### ISSUE TITLE
Query multiple layers for the same field? #19

### ISSUE THREAD

**Issue by DJA30** [tmcgee/cmv-widgets#155]
I know this issue was resolved, but is there any way I can get an example of this?

**Comment by tmcgee** [comment]
@DJA30 There is an example of using the FindTask in the Search widget's [config file](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L282-L343)

**Comment by DJA30** [comment]
can this be used with the search by shape as well? @tmcgee

**Comment by tmcgee** [comment]
Sorry, no. Esri's FindTask does not support geometry in the [parameters](https://developers.arcgis.com/javascript/3/jsapi/findparameters-amd.html).
