### ISSUE TITLE
Zoom to selected not working for some layers (on row click and drop down)

### ISSUE THREAD

**Issue by DJA30** [tmcgee/cmv-widgets#161]
@tmcgee - I am configuring the search tool currently and am running into an issue of not being able to zoom to features when I select them in the table or the drop down.  My first 3 layers work but the next 4 do not.  The resulting search is appearing in the attributes table but I don't have the zoom functions.  The snippet below is the last layer that works (Reg Station) and the first that does not (Premise).

{
                name: 'Reg Station',
                expression: '', // additional where expression applied to all queries
                idProperty: 'OBJECTID',
                queryParameters: {
                    type: 'spatial', // spatial, relationship, table or database
                    layerID: 'reg', //// **** from operational layers -- might have to change this for the CMV -bft 10-14-17
                    sublayerID: 1, ///// **** from the rest URL of the layer -bft 10-14-17
                    outFields: ['*']
                },
                attributeSearches: [{
                    // can add to this later, if we want to do attribute selections
                    name: 'Select Reg Station',
                    searchFields: [
                        {
                            name: 'Reg Station by Gas System',
                            label: 'Reg Station by Gas System',
                            expression: '(UPPER(SYSTEM_NUM) LIKE UPPER(\'%[value]%\'))',
                            placeholder: 'Enter Gas System Number',
                            required: false,
                            minChars: 2
                        }
                    ],
                    title: 'Reg Stations (Selected)',
                    topicID: 'regstationSelected',
                    gridOptions: {
                        columns: [
                            {//1
                                field: 'G3E_FID',
                                label: 'G3E_FID'
                            }, {//2
                                field: 'MXASSETNUM',
                                label: 'MX Asset Num'
                            }, {//3
								field: 'STATION_NAME',
								label: 'Station Name'
							}, {//4
								field: 'STATION_NUM',
								label: 'Station Number'
							}, {//5 and 6
                                field: 'LOCATION',
                                label: 'Location'
                            }, {//7
								field: 'TYPE',
								label: 'Type'
							}, {//8
								field: 'INSPECTABLE_F',
								label: 'Inspectable'
							}, {//9
								field: 'CUT_Q',
								label: 'Cut'
							}, {//10
								field: 'RUN_Q',
								label: 'Run'
							}, {//12
								field: 'DIAMETER_NOMINAL',
								label: 'Diameter'
							}, {//13
								field: 'SYSTEM_NUM',
								label: 'System Number'
							}, {//14
                                field: 'DATE_INSTALLED',
                                label: 'Install Date',
                                get: function (object) {
                                    return getDateTime(object.DATE_INSTALLED);
                                },
                                formatter: formatDate
                            }, {//16
								field: 'CITY_NAME',
								label: 'City'
							}, {//17
                                field: 'FACILITY_CLASS',
                                label: 'Facility'
                            }, {//18
                                field: 'OP_CENTER',
                                label: 'OP Center'
                            }, {//19
                                field: 'OP_CENTER_CSS',
                                label: 'CSS OP Center'
                            } 
                                
								

                        ]
                    }
                }

                ]
            }, {
                name: 'Premise',
                expression: '', // additional where expression applied to all queries
                idProperty: 'OBJECTID',
                queryParameters: {
                    type: 'spatial', // spatial, relationship, table or database
                    layerID: 'gas', //// **** from operational layers -- might have to change this for the CMV -bft 10-14-17
                    sublayerID: 22, ///// **** from the rest URL of the layer -bft 10-14-17
                    outFields: ['*']
                },
                attributeSearches: [{
                    // can add to this later, if we want to do attribute selections
                    name: 'Select Premise',
                    searchFields: [
                        {
                            name: 'Select by Premise',
                            label: 'Select by Premise',
                            expression: '(UPPER(PREMISE_NUM) LIKE UPPER(\'%[value]%\'))',
                            placeholder: 'Enter Premise Number',
                            required: false,
                            minChars: 2
                        }
                    ],
                    title: 'Premise (Selected)',
                    topicID: 'premiseSelected',
                    gridOptions: {
                        columns: [
                            {
                                field: 'G3E_FID',
                                label: 'G3E_FID'
                            }, {
                                field: 'PREMISE_NUM',
                                label: 'Premise Number'
                            }, {
                                field: 'HOUSE_NUM',
                                label: 'House Number'
                            }, {
								field: 'LOCATION',
								label: 'Location'
							}, {
								field: 'CITY_NAME',
								label: 'City'
							}, {
                                field: 'STATE_NAME',
                                label: 'State'
                            }, {
								field: 'COUNTY_NAME',
								label: 'County'
							}, {
                                field: 'SUBSIDIARY',
                                label: 'Subsidiary'
                            }, {
                                field: 'DATE_INSTALLED',
                                label: 'Install Date',
                                get: function (object) {
                                    return getDateTime(object.DATE_INSTALLED);
                                },
                                formatter: formatDate
                            }, {
                                field: 'OP_CENTER_CSS',
                                label: 'OP Center'
                            }, {
                                field: 'TYPE_UTILITY',
                                label: 'Utility'
                            }, {
                                field: 'COORD_X1_LL',
                                label: 'X'
                            }, {
                                field: 'COORD_Y1_LL',
                                label: 'Y'
                            }/* , {
                                field: 'FACILITY_CLASS',
                                label: 'Facility Class'
                            }, {
                                field: 'NODE1_ID',
                                label: 'Node 1 ID'
                            }, {
                                field: 'NODE2_ID',
                                label: 'Node 2 ID'
                            } */
                                
								

                        ]
                    }
                }

                ]
            },

**Comment by tmcgee** [comment]
Most often this is caused by the geometry (the `shape` field) not being included in the map service attributes or not being included in the `outFields` in the configuration for the search query.

**Comment by DJA30** [comment]
@tmcgee - so republishing the map service with the geometry included should fix the issue?

**Comment by tmcgee** [comment]
@DJA30 Another thing to verify is that the `idProperty` is the correct field and that field is included in the `outFields` in the configuration.

**Comment by DJA30** [comment]
Thanks @tmcgee the republish with the geometry included fixed the issue.  I do have one more question though.  Does the Search widget ignore the Definition Query set in Arcmap?  I have multiple layers created from the same source, but they have different Definition Queries.  When I do a search on one layer it returns rows from other layers, and I believe this is preventing the zoom to on row click and highlight ability from functioning.

**Comment by tmcgee** [comment]
@DJA30 The Search widget or any client-side code that queries the data through the AGS REST interface cannot ignore the layer's Definition Query Expression set in the Map Service via ArcMap. You can append to the expression but you cannot override it. I believe this behavior was implemented by Esri back in AGS version 10.2 or thereabouts as security measure.
