### ISSUE TITLE
Export button only works once

### ISSUE THREAD

**Issue by TheFurryCreature** [tmcgee/cmv-widgets#162]
Hi, I'm republishing this issue posted in the core cmv depository originally by @ScottBassingthwaite, which @tmcgee requested to move here. I have exactly the same issue in IE. Thanks.

**How often can you reproduce it?**

 - [x] Always
 - [ ] Sometimes
 - [ ] Rarely
 - [ ] Unable
 - [ ] I didn’t try

Export button on attribute table only works once per session

**Description:**
Can only export attribute table contents once per session

query data and produce attribute table
click export button
save file
Clear all
query data and produce attribute table
click export button
nothing happens
Refresh entire viewer
query data and produce table
click export button
save file
Clear all
query data and produce attribute table
click export button
save file

**Steps to reproduce:**

Include a JS Bin (or equivalent) link if possible. You can use this as a starting point
Detail the exact steps taken to produce the problem
Include a gif if possible; you can use LICEcap to make a gif: http://www.cockos.com/licecap/
Check the browser console for errors (Use F12 to access the console)
removeLink: function () {
if (this.link && this.divExportLink) {
this.divExportLink.removeChild(this.link);
_NotFoundError_
this.divExportLink.innerHTML = ' ';
}
this.link = null;
},

**Expected results:**
display save file

**Actual results:**
nothing

**Environment:**

 Software | Version 
 --------- | --------
CMV Version | 2.0.0 beta 2 
Browser | IE 11 
Operating system | Windows 7

**Comment by TheFurryCreature** [comment]
So I've fixed the main issue of the Dialog box not displaying due to the .removeChild() element not found. The text for the additional download _a href_ link still doesn't display in IE like it does in Google, but that is only cosmetic and not a priority at this point.  I added **if (this.divExportLink.children.length > 0)** to the removeLink function and the export button now works each time in IE11.



```
removeLink: function () {
            if (this.link && this.divExportLink) {
                if (this.divExportLink.children.length > 0) {
                    this.divExportLink.removeChild(this.link);
                    this.divExportLink.innerHTML = '&nbsp;';
                }
            }
            this.link = null;
        }
```

**Comment by TheFurryCreature** [comment]
@tmcgee How do I get the amendment added to the source code? What process must I follow?

**Comment by tmcgee** [comment]
This has been fixed
