### ISSUE TITLE
Search/Attribute Results

### ISSUE THREAD

**Issue by drusexton** [tmcgee/cmv-widgets#163]
@tmcgee is it possible to show more than 1,000 feature in the attributes table when it loads and /or when you perform a query?

**Comment by TheFurryCreature** [comment]
@drusexton The number of records returned in a query is based on a setting on the feature service. 1000 records is the default. If you want to enable a query to return more than a 1000 records in the attribute table - then you'll need to adjust the maxRecordCount. 
http://server.arcgis.com/en/server/10.3/publish-services/linux/setting-map-service-properties.htm
https://support.esri.com/en/technical-article/000012383

**Comment by drusexton** [comment]
@TheFurryCreature I know this what the heck was I thinking??? Thanks for steering me in the right direction!

**Comment by drusexton** [comment]
@TheFurryCreature I know this what the heck was I thinking??? Thanks for steering me in the right direction!
