### ISSUE TITLE
Search retrieving related fields

### ISSUE THREAD

**Issue by DJA30** [tmcgee/cmv-widgets#167]
@tmcgee is there an example of the the Search widgit pulling related fields into another tab?  
Thanks,

**Comment by tmcgee** [comment]
There is [this example](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget-relatedRecords.js) in this repo.

**Comment by DJA30** [comment]
Awesome @tmcgee , this is exactly what I needed.  Thanks

**Comment by DJA30** [comment]
@tmcgee - I receive a error message "SCRIPT438: Object doesn't support property or method 'publish'" when the the related tables section tries to run.  Am i missing a configuration somewhere for the topic/dojo?
![error example](https://user-images.githubusercontent.com/32906601/34827798-fb1dab60-f6a0-11e7-9757-04c9717f8920.PNG)

**Comment by tmcgee** [comment]
@DJA30 That suggests that your modules and variables defined at the top of the file are mismatched.

**Comment by DJA30** [comment]
@tmcgee - Thanks, that fixed it.  I do have one more question though.  Does this feature of the search tool work with only spatial layers in the viewer or does it work with non-spatial tables that have a relationship class with a spatial layer?  And sorry for the constant questions, I'm brand new to Javascript and dojo and am learning as I go.

**Comment by tmcgee** [comment]
@DJA30 This works with both related feature in feature classes and related records in tables.

**Comment by DJA30** [comment]
@tmcgee Thanks, that narrows it down to me not having my fields correct then.
