### ISSUE TITLE
Plug-in for layerControl widget

### ISSUE THREAD

**Issue by tnaberhaus** [tmcgee/cmv-widgets#17]
Is it possible now to set CMV layers to be available in the attribute table via the layerControl widget or is it still in the planning stages?

**Comment by tmcgee** [comment]
There has been progress on this by me.  Someone else may have created one.

**Comment by tmcgee** [comment]
@tnaberhaus Sorry, I meant to say there has been **NO** progress by me. There have been some enhancements to the layerControl widget by @roemhildtg that might make this pretty easy. Now that I am back at work after extended vacation, I hope to look into this in the near future.

**Comment by tnaberhaus** [comment]
Thanks Tim.  I am running the latest release of the cmv and have used the layerControl widget enhancements from @roemhildtg to create the menu items for opening the sublayer in the attributeTable as described in the docs here: https://github.com/cmv/cmv-docs/blob/master/widgets/LayerControl.md
Can you offer any additional guidance in publishing the sublayer attributes in the table when the menu item is clicked?  Is there a working example that can be shared?

**Comment by green3g** [comment]
I'm not sure how to best accomplish this. We did it by essentially creating an `invisible` widget that did the following:
1. Subscribe  to the `LayerControl/openAttributeTable`
2. When the topic is published:
3. Extract the necessary parameters from the Layer that was clicked (url, layer name, definition query, etc)
4. Publish the attributeTable's topic with the necessary parameters

This method has some obvious overhead, its essentially a proxy between the two topics/widgets but it worked really well and was simple to set up and maintain.

**Comment by tnaberhaus** [comment]
Thanks for your explanation Gregg!  These are the same steps I used yesterday to get it working by using your heatmap widget as an example.

**Comment by tmcgee** [comment]
So would an invisible "widget" (created in the config without any additional files) look something like this:

``` javascript
layerControlToTable: {
    include: true,
    id: 'layerControlToTable',
    type: 'invisible',
    path: 'dijit/_WidgetBase',
    options: {
        startup: function () {

            // subscribe to topic setup in layerControl sub menu
            topic.subscribe('layerControl/openTable', function (r) {

                // publish topic for attributes table
                topic.publish('attributesTables/addTable', {
                    title: r.layer.name',
                    topicID: r.id + '/' + r.sublayer,
                    queryOptions: {
                        queryParameters: {
                            type: 'spatial',
                            layerID: r.id,
                            subLayerID: r.sublayer,
                            outFields: ['*']
                        }
                    }
                })
            })

        }
    }
}
```

**Comment by green3g** [comment]
Yes, thats the basics. I'm not sure if its possible, but you'd also need to include `dojo/topic` somehow.. if you do know of a way without separating it into it's own module, I'd like to see it.

**Comment by tmcgee** [comment]
Sure you would need include `dojo.topic` at the top of your `viewer.js`.

I was considering adding this directly to the Attributes Table `addTopics` method if it could be done in a generic way. If you have something like my pseudo-code above actually working, perhaps you could provide a more detailed example here or better yet submit a PR?

**Comment by green3g** [comment]
Oh of course.

Here's what our approach was:

``` Javascript
define([
    'dojo/topic',
    'dojo/sniff'
], function (topic, has) {
    return {
        startup: function () {
            topic.subscribe('LayerControl/openTable', function (layer) {
                var layerDefs = (layer.layer.layerDefinitions !== null &&
                        typeof layer.layer.layerDefinitions[
layer.subLayer.id] !== 'undefined') ?
                        layer.layer.layerDefinitions[layer.subLayer.id] :
'1=1';
                topic.publish('attributesContainer/addTable', {
                    title: layer.subLayer.name,
                    topicID: layer.layer.id + layer.subLayer.id,
                    queryOptions: {
                        queryParameters: {
                            url: [layer.layer.url, '/', layer.subLayer.id
].join(''),
                            maxAllowableOffset: 100,
                            where: layerDefs
                        }
                    },
                    featureOptions: {
                        source: false
                    },
                    toolbarOptions: {
                        show: true,
                        zoom: {
                            show: true
                        },
                        'export': {
                            show: !has('ie') || has('ie') > 9
                        }
                    }
                });
            });
        }
    };
});
```

**Comment by tmcgee** [comment]
this is a useful addition that should be in the widget! :)

``` javascript
'export': {
    show: !has('ie') || has('ie') > 9
}
```

creating the where clause from the layerDefinition is nice too.
