### ISSUE TITLE
Advancedsearch Not working

### ISSUE THREAD

**Issue by AbdulSamim** [tmcgee/cmv-widgets#172]
Hi,
I am using the AdvancedSearch Widget(https://github.com/vojvod/CMV_AdvancedSearch_Widget) and have downloaded the js file associated. Once I run the widget I am getting the below error.

init.js:35 GET http://localhost:56519/js/viewer/Controller.js net::ERR_ABORTED
m.injectUrl @ init.js:35
ta @ init.js:32
a @ init.js:10
(anonymous) @ init.js:19
ja @ init.js:28
qa @ init.js:19
(anonymous) @ init.js:33
a @ init.js:10
$a @ init.js:33
f @ init.js:30
(anonymous) @ init.js:35
init.js:36 Error: scriptError
    at g (init.js:10)
    at HTMLScriptElement.<anonymous> (init.js:35)
(anonymous) @ init.js:36
(anonymous) @ init.js:14
a @ init.js:10
m.signal @ init.js:14
(anonymous) @ init.js:35
init.js:37 src: dojoLoader
init.js:37 info: (2) ["/js/viewer/Controller.js", Event]

**We are using the version JavaScript API version 3.22 in our CMV.**
Any lead on this will be of great help.

Thanks in Advance.
Samim

**Comment by tmcgee** [comment]
@AbdulSamim That widget is quite old and hasn't been updated in many years. It doesn't work with recent versions of CMV. To my knowledge there has been no response from the original developer when others have tried to reach out to that dev with issues about widgets.

The best I can suggest is to try my Search and AttributesTable widgets in this repo to see if they meet your needs.

**Comment by AbdulSamim** [comment]
@tmcgee Thanks for the info. I will use your Search widget.
