### ISSUE TITLE
Can i remove permanently dynamic map service layer from TOC ?

### ISSUE THREAD

**Issue by AbdulSamim** [tmcgee/cmv-widgets#173]
User add Dynamic Map Service layer(Group of layers) into TOC. At some point of time user wants to **remove same Dynamic Map Service layer(Group of layers) permanently from TOC**.

Any lead on this will be of great help.

**Comment by tmcgee** [comment]
CMV's layerControl widget has dojo topics to add (`layerControl/addLayerControls`) and remove (`layerControl/removeLayerControls`) layers to the widget. These are included in the  [documentation](http://docs.cmv.io/en/latest/widgets/LayerControl/) but without an example of how to use them. One example is in my [AttributesTable widget](https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable/_GraphicsMixin.js#L792-L827)

**Comment by AbdulSamim** [comment]
1. While removing layer from map using this code inside **LayerControl.js**
**this.map.removeLayer(control.layer)** required layer is removed from the map viewer, but still **this.layerInfos**  having information of removed layers. 

 OR  I am using (layerControl/removeLayerControls) in this case layer is not removed from
Map and TOC

_Removeservice: function (control) { 
            var layerControlInfo = {
                controlOptions: {
                    expanded: false,
                    noLegend: true,
                    metadataUrl: false,
                    swipe: false
                },
                layer: control.layer,
                title: control.layer.id,
                type: 'dynamic'
            };

            topic.publish('layerControl/removeLayerControls', [layerControlInfo]);
}


2. While adding dynamic service programmatically in map viewer it is adding but in TOC not getting updated.

var imageParameters = new ImageParameters();
                    imageParameters.layerIds = visibleLayers;
                    imageParameters.layerOption = ImageParameters.LAYER_OPTION_SHOW;
                    imageParameters.transparent = true;

var dynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer(url,
                    { "imageParameters": imageParameters });
this.map.addlayer(dynamicMapServiceLayer);

                     var layerControlInfo = {
                         controlOptions: {
                             expanded: false,
                             noLegend: true,
                             metadataUrl: false,
                             swipe: false
                         },
                         layer: dynamicMapServiceLayer,
                         title: 'Cities',

                         type: 'dynamic'
                     };
                     topic.publish('layerControl/addLayerControls', [layerControlInfo]);
Please let me know how to update/refresh layercontrol after adding or removing service/layer from the map. 

Any lead on this will be of great help.
Thanks in Advance.
Samim

**Comment by AbdulSamim** [comment]
Hi@tmcgee ,

Please go through the above comments, i am facing problems while using reomve and add layer code of layercontrol.

**Comment by tmcgee** [comment]
@AbdulSamim Please examine the example I provided in my [Attributes Table widget](https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable/_GraphicsMixin.js#L792-L827). Notice that an [array of layers](https://github.com/cmv/cmv-app/blob/develop/viewer/js/gis/dijit/LayerControl.js#L213-L214) is passed to the `removeLayerControls`, not array of layerInfos.

**Comment by AbdulSamim** [comment]
HI @tmcgee ,
As per your suggestion change the code for removeLayerControls  and it working fine,but still i have some issue in addLayerControls,, please go through this below code,

var txt = JSON.parse(response.d);
            var layers = [];

            if (txt) {

                debugger;

                /////////////////////////********AddingLayers*********//////////////////////////////

                var viewdata = txt[0].view_data;
                var viewdataparse = JSON.parse(viewdata);

                for (var j = 0; j < viewdataparse.Serviceinfo.length; j++) {

                    var url = viewdataparse.Serviceinfo[j].url;
                    var visibleLayers = viewdataparse.Serviceinfo[j].visiblelayers;
                    var allLayers = viewdataparse.Serviceinfo[j].layersinfo;
                    var mapExtent = viewdataparse.extent;

                    var imageParameters = new ImageParameters();
                    imageParameters.layerIds = visibleLayers;
                    imageParameters.layerOption = ImageParameters.LAYER_OPTION_SHOW;
                    imageParameters.transparent = true;

                    var dynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer(url,
                    { "imageParameters": imageParameters });


                    layers.push(dynamicMapServiceLayer);
                }

                SaveObj.map.addLayers(layers);

                var layerControlInfo = {
                    controlOptions: {
                        expanded: false,
                        noLegend: true,
                        metadataUrl: false,
                        swipe: false
                    },
                    layer: layers,
                    title: 'test',
                    type: 'dynamic'
                };

                topic.publish('layerControl/addLayerControls', [layerControlInfo]);


and i am getting an error,

init.js:28 Uncaught TypeError: layer.on is not a function
    at Object._addControl (LayerControl.js:254)
    at init.js:63
    at ja (init.js:28)
    at init.js:20
    at ka (init.js:28)
    at Qa (init.js:20)
    at c (init.js:20)
    at Object.<anonymous> (LayerControl.js:181)
    at Object.forEach (init.js:70)
    at Object.<anonymous> (LayerControl.js:173)

Thanks,
Abdul Samim

**Comment by tmcgee** [comment]
In this section of code:
``` javascript
var layerControlInfo = {
    controlOptions: {
        expanded: false,
        noLegend: true,
        metadataUrl: false,
        swipe: false
    },
    layer: layers,
    title: 'test',
    type: 'dynamic'
};
```

the `layer` property must be a single layer. You are passing in an array of layers.


try something like this:

``` javascript
var txt = JSON.parse(response.d);
var layers = [];
var layerControlInfos = [];

if (txt) {
    for (var j = 0; j < viewdataparse.Serviceinfo.length; j++) {
        var viewdata = txt[0].view_data;
        var viewdataparse = JSON.parse(viewdata);

        var url = viewdataparse.Serviceinfo[j].url;
        var visibleLayers = viewdataparse.Serviceinfo[j].visiblelayers;
        var allLayers = viewdataparse.Serviceinfo[j].layersinfo;
        var mapExtent = viewdataparse.extent;

        var imageParameters = new ImageParameters();
        imageParameters.layerIds = visibleLayers;
        imageParameters.layerOption = ImageParameters.LAYER_OPTION_SHOW;
        imageParameters.transparent = true;

        var dynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer(url, {
            'imageParameters': imageParameters
        });


        layers.push(dynamicMapServiceLayer);
        layerControlInfos.push({
            controlOptions: {
                expanded: false,
                noLegend: true,
                metadataUrl: false,
                swipe: false
            },
            layer: dynamicMapServiceLayer,
            title: 'Each Layer Name Goes Here',
            type: 'dynamic'
        });
    }

}

if (layers.length > 0) {
    SaveObj.map.addLayers(layers);
}

if (layerControlInfos.length > 0) {
    topic.publish('layerControl/addLayerControls', layerControlInfos);
}

```

**Comment by AbdulSamim** [comment]
Hi @tmcgee 

Thank you for all the help you have given with a very quick response,
I implemented the code as you suggested above,i face two more issues are that,

1. Now the layers are added in TOC and map too but the sublayres are not appears in TOC.For your more clarification i attached two images,please have a look on it. I also tried by adding sublayers:true and allSublayerToggles:true in controlOptions but still the result is same, here is below code

layerControlInfos.push({
                        controlOptions: {
                            expanded: false,
                            noLegend: true,
                            metadataUrl: false,
                            swipe: false,
                            **sublayers: true,**
                            **allSublayerToggles:true**
                        },
                        layer: dynamicMapServiceLayer,
                        title: 'Each Layer Name Goes Here',
                        type: 'dynamic'
                    });


2. After adding layers in map and TOC, while i am going for ZoomIn or ZoomOut, i am getting an error,

init.js:248 exception in animation handler for: onEnd
_fire @ init.js:248
_cycle @ init.js:251
(anonymous) @ init.js:63
c @ init.js:119
(anonymous) @ init.js:63
setInterval (async)
_startTimer @ init.js:252
_cycle @ init.js:251
_play @ init.js:249
(anonymous) @ init.js:63
play @ init.js:248
__setExtent @ init.js:590
_extentUtil @ init.js:588
_wheelZoom @ init.js:1281
(anonymous) @ init.js:63
c @ init.js:119
_fire @ init.js:1306
_onMouseWheelHandler @ init.js:1314
(anonymous) @ init.js:63
init.js:248 TypeError: Cannot read property 'getScale' of null
    at Object._checkboxScaleRange (_Control.js:211)
    at Object.<anonymous> (init.js:63)
    at Object.<anonymous> (init.js:655)
    at Object.c [as onZoomEnd] (init.js:119)
    at Object.__zoomEnd (init.js:583)
    at Object._zoomEndHandler (init.js:575)
    at d.Animation.onEnd (init.js:63)
    at d.Animation._fire (init.js:248)
    at d.Animation._cycle (init.js:251)
    at Object.<anonymous> (init.js:63)

**Error At:-**
In Control.js file

_checkboxScaleRange: function () {
            var node = this.checkNode,
                layer = this.layer,
                **scale = layer.getMap().getScale(),**
                min = layer.minScale,
                max = layer.maxScale;
            domClass.remove(node, 'layerControlCheckIconOutScale');
            if ((min !== 0 && scale > min) || (max !== 0 && scale < max)) {
                domClass.add(node, 'layerControlCheckIconOutScale');
            }
        },

[TOC_Sublayers.zip](https://github.com/tmcgee/cmv-widgets/files/1927675/TOC_Sublayers.zip)
[TOC_WithoutSublayers.zip](https://github.com/tmcgee/cmv-widgets/files/1927676/TOC_WithoutSublayers.zip)

Thanks & Regards,
Abdul Samim

**Comment by AbdulSamim** [comment]
@tmcgee I am desperately waiting for u your replay on it as i have very urgent requirement.

Thanks & Regards,
Abdul Samim

**Comment by tmcgee** [comment]
@AbdulSamim I haven't looked at your code but these errors most likely occur because you are adding the layers to the layerControl widget before they have been fully loaded by the map. You can use `once.on` like we do [here](https://github.com/cmv/cmv-app/blob/develop/viewer/js/viewer/_MapMixin.js#L87) to wait for the layers to be loaded, then proceed to add them to the layerControl widget

**Comment by AbdulSamim** [comment]
@tmcgee Actually, I saved the services in db and i loaded services from there whenever i needed in JSON format through ajax call. Before that i remove the layers which are already on the map. For removing services i add control in layercontrol menu(which working fine). Below i share my code for it. For loading layers go to the **Servicesuccessload** function. The main issue here Sublayers(On/Off(CheckBox)) are not coming in TOC. Please have a look on it.For your better understanding i also attached my UI.

var layer;
var SaveObj;
var gridlength;
var testarray;
var counter = 0;
define([
    // basics
    'dojo/_base/declare',
    'dojo/_base/lang',
    'dojo/_base/array',

    'dojo/on',
    'dojo/keys',

    'dijit/TooltipDialog',
    'dijit/popup',

    'put-selector',

    // mixins & base classes
    'dijit/_WidgetBase',
    'dijit/_TemplatedMixin',
    'dijit/_WidgetsInTemplateMixin',

    'dgrid/OnDemandGrid',
    'dgrid/Selection',
    'dgrid/Keyboard',
    'dgrid/extensions/ColumnResizer',
    'dojo/data/ItemFileWriteStore',
    'dojox/grid/DataGrid',
     'dojo/topic',
    // default coord types
    //'./GotoPoint/CoordTypes',

    //store for select
    'dojo/data/ObjectStore',
    'dojo/store/Memory',
    'dojo/dom-construct',
    'dijit/form/Button',
    //graphics layer
    'esri/graphic',
    'esri/geometry/Point',
    'esri/SpatialReference',
    './GotoPoint/images/icon',
    'esri/symbols/PictureMarkerSymbol',
    'esri/layers/ArcGISDynamicMapServiceLayer',
    "esri/layers/ImageParameters",
     'esri/layers/LayerInfo',
    // templates & widget css
    'dojo/text!./SaveLoadService/templates/SaveLoadService.html',
    'xstyle/css!./SaveLoadService/css/SaveLoadService.css',

    // not referenced

    'dijit/form/TextBox',
    'dijit/form/Select'
], function (
    declare, lang, array,
    on, keys,
    TooltipDialog, popup,
    put,
    _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin,
    OnDemandGrid, Selection, Keyboard, ColumnResizer, ItemFileWriteStore, DataGrid, topic,
    ObjectStore, Memory, domConstruct, Button,
    Graphic, Point, SpatialReference, icon, PictureMarkerSymbol,
    ArcGISDynamicMapServiceLayer,
    ImageParameters, LayerInfo,
    template
) {

    return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
        widgetsInTemplate: true,
        templateString: template,
        baseClass: 'gis_SaveLoadServiceDijit',
        graphicCoordinate: null,
        _setGraphicCoordinateAttr: function (coordinate) {
            this.graphicCoordinate = coordinate;
            if (coordinate) {
                var point = new Point(coordinate, new SpatialReference({
                    wkid: 4326
                }));
                this.graphic.setGeometry(point);
                this.graphic.show();
            } else {
                this.graphic.hide();
            }
        },

        postCreate: function () {

            this.inherited(arguments);
            SaveObj = this;
            var setOption = function (rowObj) {

                var cellContent = domConstruct.create("div", {});

                var btnload = new Button({
                    //iconClass: 'dijitIconLoad',
                    //showLabel: false,
                    label: 'Load',
                    name: rowObj.UserName,
                });
                btnload.placeAt(cellContent);


                on(btnload, "click", function (evt) {


                    ////////////////////////////*************************/////////////////////////////////

                    var namedata = evt.srcElement.name;

                    $.ajax({
                        type: "POST",
                        url: window.location.origin + "/SLNSDIMapServices/Service.asmx/Getgistables",
                        data: "{ViewName:'" + namedata + "'}",
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: SaveObj.Servicesuccessload,
                        error: SaveObj.showError
                    });

                    /////////////////////////////************************/////////////////////////////////

                    alert('Load clicked');
                });


                var btnupdate = new Button({
                    //iconClass: 'dijitIconFolderClosed',
                    //showLabel: false,
                    label: 'Update',
                    name: rowObj.UserName
                });
                btnupdate.placeAt(cellContent);

                on(btnupdate, "click", function (evt) {
                    var newmap = SaveObj.map;

                    var Layerstable;

                    var Serviceinfo = [];

                    for (var i = 0; i < newmap.layerIds.length; i++) {

                        if (newmap.layerIds[i] != 'layer0') {

                            layer = null;

                            layer = SaveObj.map.getLayer(SaveObj.map.layerIds[i]);

                            if (layer.supportsDynamicLayers) {

                                Serviceinfo.push(
                                 {
                                     "type": "dynamic",
                                     "url": layer.url,
                                     "title": layer.id,
                                     "options": {
                                         "id": layer.id,
                                         "visible": layer.visible,
                                         "sublayers": "true"
                                     },
                                     "layersinfo": layer.layerInfos,
                                     "visiblelayers": layer.visibleLayers
                                 }

                               )
                            }
                        }
                        else {

                            //Write for Base Layers
                        }
                    }

                    Layerstable = {
                        "viewname": dijit.byId('txtSave').value,
                        "extent": SaveObj.map.extent,
                        "Serviceinfo": Serviceinfo
                    }


                    ////////////////*********************************************//////////////////////////////////

                    var strdata = JSON.stringify(Layerstable);
                    var namedata = evt.srcElement.name;

                    $.ajax({
                        type: "POST",
                        url: window.location.origin + "/SLNSDIMapServices/Service.asmx/UpdateViewData",
                        data: "{ViewName:'" + namedata + "',ViewData:'" + strdata + "'}",
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: SaveObj.Servicesuccessupdate,
                        error: SaveObj.showError
                    });

                    //////////////////////*********************************************///////////////////////////////////

                    alert('Update clicked');
                });


                var btndelete = new Button({
                    //iconClass: 'dijitIconFolderClosed',
                    //showLabel: false,
                    label: 'Delete',
                    name: rowObj.UserName
                });
                btndelete.placeAt(cellContent);

                on(btndelete, "click", function (evt) {

                    var namedata = evt.srcElement.name;

                    $.ajax({
                        type: "POST",
                        url: window.location.origin + "/SLNSDIMapServices/Service.asmx/DeleteViewData",
                        data: "{ViewName:'" + namedata + "'}",
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: SaveObj.Servicesuccessdelete,
                        error: SaveObj.showError
                    });


                    for (var i = 0 ; i < testarray.length; i++) {
                        if (testarray[i].UserName == namedata)
                            testarray.splice(i, 1);
                    }


                    SaveObj.resultsGrid.store.setData(testarray);
                    SaveObj.resultsGrid.refresh();

                    alert('Delete clicked');
                });

                return cellContent;
            };

            ///////////*********************//////////.

            SaveObj.resultsStore = new Memory({
                idProperty: 'id',
                data: []
            });

            var Grid = declare([OnDemandGrid, Keyboard, Selection, ColumnResizer]);
            SaveObj.resultsGrid = new Grid({
                selectionMode: false,
                cellNavigation: false,
                showHeader: true,
                store: SaveObj.resultsStore
            }, SaveObj.findResultsGrid);
            SaveObj.resultsGrid.startup();


            SaveObj.resultsStore.setData([]);

            SaveObj.resultsGrid.refresh();


            SaveObj.findResultsGrid.style.display = 'none';


            var columns = {
                ID: 'User ID',
                UserName: 'User Name',
                Options: {
                    renderCell: function (obj) {
                        return setOption(obj);
                    }
                }
            }

            SaveObj.resultsGrid.setColumns(columns);

            //////////////////////////////////***************///////////////////////////////////

            ////////////////////////////*************************/////////////////////////////////

            var namedata = 'All';

            $.ajax({
                type: "POST",
                url: window.location.origin + "/SLNSDIMapServices/Service.asmx/Getgistables",
                data: "{ViewName:'" + namedata + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: this.Servicesuccessloadpost,
                error: this.showError
            });

            /////////////////////////////************************/////////////////////////////////


        },

        //startup: function () {
        //    debugger;
        //    this.inherited(arguments);
            
        //    //this.layoutDeferred.then(lang.hitch(this, 'initMapAsync'));
        //},

        save: function () {
            debugger;
            var newmap = this.map;

            var Layerstable;

            var Serviceinfo = [];

            for (var i = 0; i < newmap.layerIds.length; i++) {

                if (newmap.layerIds[i] != 'layer0') {

                    layer = null;

                    layer = this.map.getLayer(this.map.layerIds[i]);

                    if (layer.supportsDynamicLayers) {

                        Serviceinfo.push(

                         {
                             "type": "dynamic",
                             "url": layer.url,
                             "title": layer.id,
                             "options": {
                                 "id": layer.id,
                                 "visible": layer.visible,
                                 "sublayers": "true"
                             },
                             "layersinfo": layer.layerInfos,
                             "visiblelayers": layer.visibleLayers
                         }

                       )
                    }
                }
                else {

                    //Write for Base Layers
                }
            }

            Layerstable = {
                "viewname": dijit.byId('txtSave').value,
                "extent": this.map.extent,
                "Serviceinfo": Serviceinfo
            }


            ////////////////*********************************************//////////////////////////////////

            var strdata = JSON.stringify(Layerstable);
            var namedata = dijit.byId('txtSave').value;

            $.ajax({
                type: "POST",
                url: window.location.origin + "/SLNSDIMapServices/Service.asmx/InsertViewData",
                data: "{ViewName:'" + namedata + "',ViewData:'" + strdata + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: this.Servicesuccessget,
                error: this.showError
            });

            //////////////////////*********************************************///////////////////////////////////

            this.updategridview(dijit.byId('txtSave').value);

            alert('save');
        },

        updategridview: function (name) {
            counter++
            testarray.push({
                ID: gridlength + counter,
                UserName: name
            });

            SaveObj.resultsGrid.store.setData(testarray);
            SaveObj.resultsGrid.refresh();
        },

        Servicesuccessget: function (response) {
            alert('Inserted Properly');
        },

        Servicesuccessupdate: function () {
            alert('Updated Successfully');
        },

        Servicesuccessdelete: function () {
            alert('Delete Successfully');
        },

        Servicesuccessload: function (response) {
            var txt = JSON.parse(response.d);
            var layers = [];
            var layerControlInfos = [];

            if (txt) {

                debugger;

                var viewdata = txt[0].view_data;
                var viewdataparse = JSON.parse(viewdata);

                /////////////////////////********AddingLayers*********//////////////////////////////

                for (var j = 0; j < viewdataparse.Serviceinfo.length; j++) {

                    var url = viewdataparse.Serviceinfo[j].url;
                    var visibleLayers = viewdataparse.Serviceinfo[j].visiblelayers;
                    var allLayers = viewdataparse.Serviceinfo[j].layersinfo;
                    var mapExtent = viewdataparse.extent;

                    var imageParameters = new ImageParameters();
                    imageParameters.layerIds = visibleLayers;
                    imageParameters.layerOption = ImageParameters.LAYER_OPTION_SHOW;
                    imageParameters.transparent = true;

                    var dynamicMapServiceLayer = new ArcGISDynamicMapServiceLayer(url,
                    { "imageParameters": imageParameters });

                    layers.push(dynamicMapServiceLayer);

                    layerControlInfos.push({
                        controlOptions: {
                            expanded: true,
                            noLegend: true,
                            metadataUrl: true,
                            swipe: true,
                            sublayers: true,
                            allSublayerToggles:true
                        },
                        layer: dynamicMapServiceLayer,
                        title: viewdataparse.Serviceinfo[j].title,
                        type: 'dynamic'
                    });
                }

                if (layers.length > 0) {
                    SaveObj.map.addLayers(layers);
                }

                //on.once(SaveObj.map, 'layers-add-result', lang.hitch(SaveObj, '_onLayersAddResult', layerControlInfos));

                if (layerControlInfos.length > 0) {
                    topic.publish('layerControl/addLayerControls', layerControlInfos);
                }

                //////////////////////////*******************////////////////////////////////////////

                alert('Loaded Successfully');
            }
        },
        _onLayersAddResult: function (layerControlInfos) {
            debugger;
            if (layerControlInfos.length > 0) {
                topic.publish('layerControl/addLayerControls', layerControlInfos);
            }
        },

        Servicesuccessloadpost: function (response) {
            var txt = JSON.parse(response.d);
            var layers = [];
            testarray = [];

            if (txt) {

                /////////////////////////********AddingGridView*********//////////////////////////////

                for (var k = 0; k < txt.length; k++) {

                    testarray.push({
                        ID: k + 1,
                        UserName: txt[k].name
                    });
                }

                SaveObj.resultsGrid.store.setData(testarray);
                SaveObj.resultsGrid.refresh();

                var lyrDisplay = 'block';
                SaveObj.resultsGrid.styleColumn('layerName', 'display:' + lyrDisplay);
                SaveObj.findResultsGrid.style.display = 'block';

                //////////////////////////*******************////////////////////////////////////////

                gridlength = SaveObj.resultsGrid.store.data.length;
            }
        },

        showError: function (result) {
            alert('Error');
        }

    });
});

[Save & Load UI.zip](https://github.com/tmcgee/cmv-widgets/files/1934284/Save.Load.UI.zip)

Thanks,
Abdul Samim

**Comment by AbdulSamim** [comment]
@tmcgee Please review the above code.
Thanks & Regards,
Abdul Samim

**Comment by AbdulSamim** [comment]
@tmcgee May I know if there is any new update on above code  i totally stuck here?
Thanks & Regards,
Abdul Samim

**Comment by tmcgee** [comment]
@AbdulSamim Obviously I can't test all that you have going on since your layers are retrieved from elsewhere. Based on my reading your code, I still believe that my previous comment is your issue. You are not waiting for this call:

``` javascript
SaveObj.map.addLayers(layers);
```

to finish before the layers are added to the layerControl widget.  Sorry, I really can't assist 
 with troubleshooting a heavily customized application.
