### ISSUE TITLE
How can i display  Domain Value instead of Domain code in Attribute Table??

### ISSUE THREAD

**Issue by AbdulSamim** [tmcgee/cmv-widgets#176]
I have layer with domain values and domain code. In Attribute Table widget by default it is showing code for the field which having domain.So my requirement is to display domain value(Description) instead of code for user understanding.

Thanks & Regards,
Abdul Samim

**Comment by tmcgee** [comment]
This was implemented a few months back for both the Attributes Table and Search Widgets.
