### ISSUE TITLE
How to setup export widget to export drawn graphics

### ISSUE THREAD

**Issue by Zxcvbnm87** [tmcgee/cmv-widgets#184]
Hi,

Just wondering how to actually setup the Export widget to export graphics created with the draw tool. Out of the box it doesn't seem to work so I'm probably missing something.

**Comment by tmcgee** [comment]
@JMaps88 You're not missing anything. Out of the box, the Draw widget has no export capabilities. I have wired in the those export capabilities into some custom Draw tools built for clients using the Export widget so it definitely is possible.
