### ISSUE TITLE
Heatmap Widget for selected features of dynamic layers

### ISSUE THREAD

**Issue by durga-pericherla** [tmcgee/cmv-widgets#185]
Hi, In the heatmap widget( https://github.com/tmcgee/cmv-widgets/tree/master/widgets/HeatMap ), is it possible to create heatmap for dynamic layers (such that I can create heatmap of only selected fetures of dynamic layer)? If so, how can I do that? 

Thanks in advance.

**Comment by tmcgee** [comment]
@ParkShinYoo That currently isn't supported in the HeatMap widget. I have considered adding in the future support for a url or a subLayer ID in the optional [layers array configuration](https://github.com/tmcgee/cmv-widgets/blob/master/config/heatmap.js#L72-L74). That would allow you to use a layer from a dynamic layer for the heatmap.

That future enhancement by itself would not use `only selected features` for a heatmap. You could use the draw tools to select within an area. If you are interested in selecting features via attributes, that is not currently supported. I have considered a future enhancement to connect the heatmap widget to my AttributesTable widget which might assist with that.

**Comment by durga-pericherla** [comment]
Thanks @tmcgee , Can you give an example (sample code) for the layer array configuration of dynamic layers.

**Comment by tmcgee** [comment]
@ParkShinYoo Unfortunately, I cannot provide an example because, as I said above, using a dynamic layer is not currently supported.

**Comment by durga-pericherla** [comment]
Ok @tmcgee, Thank you. Actually my requirement is to create the heatmap for the filtered results of the filter widget ( https://github.com/roemhildtg/cmv-widgets/blob/master/widgets/Filter ) either for dynamic or feature service layers. But the filter widget is supporting only dynamic layers not feature layers. Whereas I used another heatmap widget ( https://github.com/ERS-Long/HeatMap ) it supports dynamic layers but it is creating the heatmap based on layerwise, But I require the heatmap of the displayed data(filtered result). Is it possible ?

**Comment by tmcgee** [comment]
@ParkShinYoo It seems to me the same filter from the dynamic sub layer could be applied to the feature layer created [here](https://github.com/ERS-Long/HeatMap/blob/master/HeatMap.js#L47-L52) or [here](https://github.com/tmcgee/cmv-widgets/blob/master/widgets/Heatmap.js#L378-L383).

**Comment by durga-pericherla** [comment]
@tmcgee, I am new to the Java Script and CMV. Can you help me how to apply the Dynamic Sub layer filter to Feature layer created in the Heatmap ( https://github.com/ERS-Long/HeatMap/blob/master/HeatMap.js#L47-L52 ).

Thanks in Advance

**Comment by tmcgee** [comment]
@ParkShinYoo This is untested but it might look something like this:

``` javascript
var heatmapFeatureLayerOptions = {
     mode: FeatureLayer.MODE_SNAPSHOT,
     infoTemplate: infoTemplate,
     outFields: ['*']
};
heatmapFeatureLayer = new FeatureLayer(serviceURL, heatmapFeatureLayerOptions);

// get the layer definition from the dynamic layer;
var filterExpression = r.layer.layerDefinitions(r.sublayer.id);
if (filterExpression) {
    // set the definition expression for the feature layer
    heatmapFeatureLayer.setDefinitionExpression(filterExpression);
}
```

**Comment by durga-pericherla** [comment]
@tmcgee after modifying the code as mentioned above in heatmap.js, Heatmap is not getting created (is not functioning) with and without applying the filter.

**Comment by durga-pericherla** [comment]
@tmcgee Export button(https://github.com/tmcgee/cmv-widgets/tree/master/widgets/Export) is working fine for Excel & CSV whereas as for shafefile, .kml, .kmz, .geojson it was showing "Error during Export" popup. I couldn't figure out where the issue is. 

 Thank you.

**Comment by tmcgee** [comment]
This type of error usually occurs when there is no geometry for the features (`SHAPE` field is not included in the query) or when 1 or more features has missing or invalid geometry. 

Edit: Please create a new issue instead of adding to an unrelated issue.

**Comment by durga-pericherla** [comment]
@tmcgee sorry I will create a new issue(after checking the geometry of the features). Regarding the heatmap it's not being created after I modified the code as suggested above. Can you please help me.

Thank You.

**Comment by tmcgee** [comment]
On second look, I think the one line should have been brackets instead of parentheses:
``` javascript
var filterExpression = r.layer.layerDefinitions[r.sublayer.id];
```

still untested.

**Comment by durga-pericherla** [comment]
@tmcgee Thanks a lot. Its working now.
