### ISSUE TITLE
Query multiple layers for the same field?

### ISSUE THREAD

**Issue by AllisonBell99** [tmcgee/cmv-widgets#19]
Hi,
Is there a way to configure the search widget to search multiple layers for the same information? (multiple sublayerIDs or multiple urls that include the layerindex)
Thanks,
Ally

**Comment by AllisonBell99** [comment]
Also, is there a way to show the coded values from a domain instead of the actual value in the grid?

**Comment by tmcgee** [comment]
Finding features across sub layers (providing multiple layerIDs) is now possible using the Search widget. This was accomplished by adding the same functionality used by the CMV core Find widget.
