### ISSUE TITLE
Search widget Spatial serach error

### ISSUE THREAD

**Issue by cmccullough2** [tmcgee/cmv-widgets#190]
I am running into a new issue with the Search spatial functionality.  When I perform a spatial select I receive this error. I have minified this widget, hence the S. in the S.toJson message. 
![image](https://user-images.githubusercontent.com/3169799/46220143-e4c6ea80-c30e-11e8-8582-c093c2deba19.png)

**Comment by tmcgee** [comment]
@cmccullough2 Is the spatial reference of the map something other than 4326 or 102100? If so, a Geometry Service is used to generate the buffer geometry. While I can't tell for sure, based on my best interpretation of the error, it appears that the geometry returned from that service does not have an extent. You can check the network tab of the Chrome console to review the request to that service and the response.

P.S. Based on the line numbers, the AttributesTable widget itself does not appear to be minified. The reference to `S` variable within `init.js` is within the Esri JavaScript API.  The line numbers presented suggest that you are using an older version of the widget so I can't tell exactly which exact lines are involved.

**Comment by cmccullough2** [comment]
The spatial reference is 102100.  I also migrated from 3.21.to 3.25.  I may just have to upgrade the widget.  I have been meaning to, but I am so swamped with day to day tasks.  Thank you for the quick reply.

**Comment by tmcgee** [comment]
Ok. Presuming that this is a somewhat recent version of the the widget, with 102100, the buffer is determined by the Geometry Engine. A few questions to work through:

1. Is it a feature on the map being buffered?

2. Is it possible the feature being buffered does not have a `SHAPE` field and thus no geometry to buffer? 

3. Does the buffer display on the map while using the Search widget BEFORE pressing the search button? 

4. Does the spatial search work without buffering?

**Comment by cmccullough2** [comment]
Is it a feature on the map being buffered?  the buffer works

Is it possible the feature being buffered does not have a SHAPE field and thus no geometry to buffer?A SHAPE field is present

Does the buffer display on the map while using the Search widget BEFORE pressing the search button? Yes

Does the spatial search work without buffering? No

The network may be causing the hiccup disallowing the completion of the results.  I am befuddled.

**Comment by cmccullough2** [comment]
Steps I am completing
1. Apply a 300 Mile buffer
2. Select Features by Point
3. Click Map
3. Graphic shape is on the map
4. Click Search button
5. Shape disappears
6. Stop Drawing and Search button goes grey

**Comment by tmcgee** [comment]
Odd. Those steps work on the demo: https://tmcgee.github.io/cmv-widgets/demo.html?config=search

**Comment by cmccullough2** [comment]
Yes they do work. I checked it to see what I am supposed to be looking
for.  I am going to double check this capability outside of our network.
Sometime the network will deny transactions.   The functionality stopped
working all of a sudden.  I am not sure what happened.  I have not worked
on the widget in some time.
