### ISSUE TITLE
Mapillary widget not working

### ISSUE THREAD

**Issue by durga-pericherla** [tmcgee/cmv-widgets#191]
Hai, I am trying to add the mapillary widget in my viewer but I am encountering with the below error. When I tried to open the mapillary demo (http://tmcgee.github.io/cmv-widgets/demo.html?config=mapillary) the same error is being encountered. Can anyone please help me.
Thanks in Advance.

Loading failed for the <script> with source “https://unpkg.com/mapillary-js@2.5.2/dist/mapillary.min.js”. demo.html:1
Error: "scriptError"
ghttps://js.arcgis.com/3.21compact/:10:382hhttps://js.arcgis.com/3.21compact/:35:210 3.21compact:36:495
src: dojoLoader 3.21compact:37:36
info: 
Array [ "https://unpkg.com/mapillary-js@2.5.2/dist/mapillary.min.js", error ]
3.21compact:37:36
. 3.21compact:37:60

**Comment by tmcgee** [comment]
@ParkShinYoo I cannot reproduce this issue. The demo works fine at this time. Perhaps it was a short-term problem accessing that file that is now resolved or that server is blocked from your location for some reason.
