### ISSUE TITLE
Ability to group widgets together?

### ISSUE THREAD

**Issue by Zxcvbnm87** [tmcgee/cmv-widgets#193]
Not really an issue, more if a question. Has anyone come up with an easy way to group multiple titlepane widgets together, possibly using tabs? Similar to the search fidgets multiple tabs but with different widgets.

**Comment by tmcgee** [comment]
@JMaps88 There is an example of grouping 2 widgets [here](https://github.com/tmcgee/cmv-widgets/blob/master/config/zoomToFeature-multiple.js). They are not within tabs in that example but a similar approach is possible using tabs.

**Comment by Zxcvbnm87** [comment]
Awesome. Thank you once again

**Comment by Zxcvbnm87** [comment]
So using your example I got it to work rather easily, however the widget contents only seem to display if I set open: true. If I set it as false nothing will load. Is this a commen problem and is there a work around?

**Comment by tmcgee** [comment]
@JMaps88 Have you tried using `preload: true` instead of `open: true`? That should load the required content without having the titlepane open at startup.

**Comment by Zxcvbnm87** [comment]
Worked a treat. Thanks again for all your help
