### ISSUE TITLE
Goto map from attr table

### ISSUE THREAD

**Issue by Denverino** [tmcgee/cmv-widgets#194]
If i have dynamic layer with cache, then goto to object on map from attribute table working not correctly

**Comment by tmcgee** [comment]
@Denverino The attribute tables is not directly tied to an existing map layer other than to optionally get the REST url to search.

The most common cause for not zooming to the feature on the map from the attributes table is using the wrong `idProperty` (name of unique field) in the search's configuration. [`queryParameters` example](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L30) The field you use as the idProperty must be included in the `outFields`

**Comment by Denverino** [comment]
@tmcgee i will check my config searchWidget tomorrow. Thanks for the answer. I didn't think that attr. table widget use search widget for zooming on the map.

**Comment by Denverino** [comment]
I checked my search config. It's correct. So when i search objects with it and open arribute table, zooming object on the map works correctly. But if i open attribute table from subLayerMenu zoomin get me different objects.

**Comment by Denverino** [comment]
Interest moment that objects zoomed on the map by click going from the end to the begin of the OBJECTID of the layer...

**Comment by Denverino** [comment]
@tmcgee Oh...i fixed it...idProperty in topic.subscribe need right register of the name 'objectid'. You were rigth!
