### ISSUE TITLE
TogglePane

### ISSUE THREAD

**Issue by danielkmog** [tmcgee/cmv-widgets#2]
Sorry if I've posted this in the wrong location. I'm attempting to modifying the AttributeTable widget to toggle the pane if no results are found. I was wondering if I could get some guidance on this or possibly submit it as an enhancement request.

Thank you,
Daniel

**Comment by tmcgee** [comment]
This is the one of several places for your question. gis.stackexchange.com is another option. 

Adding this as an option within the widget is a possible enhancement.  Perhaps just not opening the pane if there are no results whereas now it opens it regardless I think. 

There is also a way to do this currently from outside the widget.  You would do this by subscribing to the appropriate topic published by the attributes table.  Then respond to no results by closing the pane (again via topic with topic.publish). I am using mobile so don't have easy access to provide you a reference.  The available topics are listed in the docs for the widget.
