### ISSUE TITLE
Need a little help defining the which attributes are shown in attributesTable widget

### ISSUE THREAD

**Issue by MesquiteGIS** [tmcgee/cmv-widgets#20]
I'm having difficultly defining which attributes show up as columns in the attributesTable widget. This is what I have which doesn't work:

attributesTable: {
      include: true,
      id: 'attributesContainer',
      type: 'domNode',
      srcNodeRef: 'attributesContainer',
      path: 'gis/dijit/AttributesTable',
      options: {
        map: true,
        mapClickMode: true,
        // use a tab container for multiple tables or
        // show only a single table
        useTabs: true,
        // used to open the sidebar after a query has completed
        sidebarID: 'sidebarBottom',
        // optional tables to load when the widget is first instantiated
        tables: [],

```
  },
  gridOptions: {
        columns: [
                { label: 'Section ID', field: 'SectionID'},
                { label: 'Street Name', field: 'FullStreetName' },
                { label: 'Begin Point', field: 'BeginPoint' },
                { label: 'End Point', field: 'EndPoint' },
        ],



  },
}
```

Thanks!

**Comment by tmcgee** [comment]
That is not the correct location for the grid options.

If using only the attributes table widget (no search), they would be defined in the options for the table in the array of tables [here](https://github.com/tmcgee/cmv-widgets/blob/master/config/table.js#L70)

If you are using the search widget, they would be defined in the options for the search [like here](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L51)

**Comment by MesquiteGIS** [comment]
Tim, 

Thank you for the help. I'm actually using the widget with the advanced search widget authored by vojvod, if that clarifies things.

**Comment by tmcgee** [comment]
Oh, then you're better off posting your question in vojvod's repo. I am not at all familiar with how that widget is configured.

**Comment by MesquiteGIS** [comment]
That was helpful! Got it to work. Thank you Tim, much appreciated!
