### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-widgets#200]
How to add a text 'Loading' in the MapLoading widget? Thanks!

**Comment by tmcgee** [comment]
@ERS-Long That isn't supported in the current implementation. It adds a single <I> element for the Font-Awesome icon. Changing the code would be required. Pull Requests welcome! 😁

**Comment by ERS-Long** [comment]
thanks for the reply, got a quick dirty version running in my local, I will try a pr this weekend. :)
