### ISSUE TITLE
open attribute table from sublayer

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-widgets#21]
Hi, Tim:

I am trying to implement the functionality to open attribute table from sublayer, here is my code

```
        topic.subscribe('LayerControl/openAttributeTable', function (r) {
            console.log(r.layer.url); //layer id
            console.log(r.subLayer.id); //array of set visible layer ids

            var data_list = [ 
                { 
                    title: 'AttributesTable', 
                    topicID: 'AttributesTable',
                    queryOptions: {
                        queryParameters: {
                            url: r.layer.url + '/' + r.subLayer.id,
                            maxAllowableOffset: 100,
                            where: '1=1'
                        },
                        idProperty: 'ObjectID'
                    }
                } 
            ]; 
            console.log(data_list);

            this.addTables(data_list);
            //this.tables = data_list;
        });
```

I put the above code in your AttributesTable.js file's postCreate method, but somehow i got this error

Uncaught TypeError: this.addTables is not a function

Please let know if you have some suggestion on this.

Thanks a lot!

**Comment by tmcgee** [comment]
This sounds like a scope issue. You can use `lang.hitch(this, function (r) {...})` to put the function in the correct scope.

2 unsolicited comments ;)
1. Don't modify `AttributesTable.js`. Separate your application code from the widget code. Consider placing this code in your own widget or in `viewer.js`. If there is something unsupported in my widgets that you need, please submit a PR or an issue because chances are others need it too.
2. Use `topic.publish('attributesContainer/addTables', dataList)`. That is a better way to do what you want (and what my Search widget does). With this, your code can live elsewhere and you don't have to modify AttributesTable.js.

**Comment by ERS-Long** [comment]
Thank you sir, Got it working

I create an invisible widget, and put all my code there, (Leave your code untouched. :) )

define([
    'dojo/_base/declare',
    'dijit/_WidgetBase',
    'dijit/_TemplatedMixin',
    'dijit/_WidgetsInTemplateMixin',
    'dojo/_base/lang',
    'dojo/dom', 
    'dojo/domReady!',
    'dojo/on',
    'dojo/topic',
    'dojo/text!./OpenAttributeTable/templates/OpenAttributeTable.html',
    'dojo/_base/array',
    'dojo/dom-construct'

], function (declare, _WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin, lang, dom, ready, on, topic, Template, arrayUtils, domConstruct) {

```
return declare([_WidgetBase, _TemplatedMixin, _WidgetsInTemplateMixin], {
    widgetsInTemplate: true,
    templateString: Template,

    postCreate: function(){
        this.inherited(arguments);

        topic.subscribe('LayerControl/openAttributeTable', function (r) {
            console.log(r.layer.url); //layer id
            console.log(r.subLayer.id); //array of set visible layer ids

            var data_list = [ 
                { 
                    title: 'AttributesTable', 
                    topicID: 'AttributesTable',
                    queryOptions: {
                        queryParameters: {
                            url: r.layer.url + '/' + r.subLayer.id,
                            maxAllowableOffset: 100,
                            where: '1=1'
                        },
                        idProperty: 'ObjectID'
                    }
                } 
            ]; 
            console.log(data_list);
            topic.publish('attributesContainer/addTables', data_list)
        });

    },
});
```

});

**Comment by ERS-Long** [comment]
Hi, Tim:

Got a quick version of the clustering point map working in CMV.

Please let others know if they want to try it out.

https://github.com/ERS-Long/PointClustering

Thanks.

**Comment by tmcgee** [comment]
@ERS-Long Nice! Can you create a PR in the [Contributed Widgets repo](https://github.com/cmv/cmv-contrib-widgets) so others can find it? Thank you.
