### ISSUE TITLE
Nearby function doesnot work with feature services?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#210]
I try to use the nearby function with feature services but they don't appear in the list to make the nearby? Do you think its possible?
 populateLayerSelect: function() {
            var options = [];
            array.forEach(this.map.layerIds, lang.hitch(this, function(layerId, i) {
                if (i !== 0) {
                    if (this.map.getLayer(layerId).layerInfos && this.map.getLayer(layerId).layerInfos.length > 0) {
                        array.forEach(this.map.getLayer(layerId).layerInfos, lang.hitch(this, function(layerInfo, j) {
                            options.unshift({
                                value: layerId + ':' + j,
                                label: layerInfo.name
                            });
                        }));
                    } else if (this.map.getLayer(layerId).name) {
                        options.unshift({
                            value: layerId + ':',
                            label: this.map.getLayer(layerId).name
                        });
                    }
                }
            }));
            this.nearbyFeaturesSelect.addOption(options);
            this.setupSelectionLayers(this.nearbyFeaturesSelect.get('value'));
        },
![image](https://user-images.githubusercontent.com/6784515/58727729-1ff44e80-83b3-11e9-9db1-933002bd0825.png)

**Comment by tmcgee** [comment]
This is not one of my custom widgets and it is not a widget that use for applications. You should try asking this question of the developer of widget you are using.

**Comment by GilbertLasnier** [comment]
Sorry I think that you created that function???

**Comment by tmcgee** [comment]
Maybe it is [this one?](https://github.com/BrianBunker/cmv-widgets/tree/master/Nearby)

**Comment by GilbertLasnier** [comment]
EXactle its that one It work with mapserver services but doesnot work with featurelayer services…Thanks
Be the way its work in your version 2.0…
