### ISSUE TITLE
Cannot format field as a Date field using the AttributeTable widget

### ISSUE THREAD

**Issue by MesquiteGIS** [tmcgee/cmv-widgets#22]
Just as the title says, I cannot get my Attribute table to format one of my fields as a date. if no columns are defined under gridOptions, the field is automatically shown as date, but when defined, I get an error message "Uncaught ReferenceError: formatDateTime is not defined".

My code looks like this:

gridOptions: {
                        columns:[
                                { label: 'Section ID', field: 'SectionID', width: 100,},
                                { label: 'Street Name', field: 'FullStreetName', width: 170, },
                                { label: 'Begin Point', field: 'BeginPoint', width: 170, },
                                { label: 'End Point', field: 'EndPoint', width: 170, },
                                { label: 'Surface Condition Rating', field: 'SurfaceConRating', width: 100, },
                                { label: 'Drainage Rating', field: 'DrainageRating', width: 150, },
                                { label: 'Evaluated', field: 'EvalDate', width: 150,  get: function (object) { // allow export as a proper date
                                        return new Date(object.EvalDate);
                                    },
                                    formatter: formatDateTime},
                                { label: 'Evaluated By', field: 'EvalBy', width: 100, },  
                        ],
                    },

Any suggestions?

**Comment by carrbrpoa** [comment]
formatDateTime must be a known function. Try to declare a function like this on top of your .js file:

``` javascript
function formatDateTime (value) {
    if (!value) return '';

    var date = new Date(value);
    return locale.format(date, {
        formatLength: 'short'
    });
}
```

PS: My config declaration has _dojo/date/locale_ injected, this is why there's a _locale_ variable in my function.

**Comment by tmcgee** [comment]
Thanks @carrbrpoa!

@MesquiteGIS: To see everything in one place refer to the [widget config in this repo](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js).

**Comment by MesquiteGIS** [comment]
Got it! Thank you, @carrbrpoa , @tmcgee 

Much appreciated!
