### ISSUE TITLE
Report widget upgrade to js 3.37

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-widgets#234]
Hi @tmcgee, 

Tried your wonderful report widget and it works perfectly until we decided to upgrade our viewer to js API beyond 3.30. After that version (starting from 3.31 to 3.37), the widget is not working anymore. I tried to update that loadJSPDF function to load most current jspdf (v2.3.1) and autotable plugin (3.5.17) in conjunction with js api 3.37, but seems it does not go anywhere. 

Please if you have time to look into it or give me some hint on how to upgrade it.

Thanks,

**Comment by tmcgee** [comment]
Hi @ERS-Long The demo in this repo is running version 3.31 and the report widget works. for me I just tried all versions from 3.31 to 3.38 locally. Everything worked as expected through version 3.36. With a quick investigation, it appears something has changed in version 3.37 that affects the ReportReactor widget (such simple code!), perhaps the Report widget as well.

I'd suggest using the code directly from this repo and a version of 3.36 or lower. As time permits I will look at the new version 3.37 and not-yet-released 3.38 to see if I can determine what may have changed to conflict with the widget(s)

**Comment by ERS-Long** [comment]
Thanks @tmcgee. I download this repo again, yes, it works just fine with 3.36.

Great and very useful widget as always. 

Appreciated!

**Comment by ERS-Long** [comment]
Hi @tmcgee managed to get the widget working in 3.37 by using the following code from ESRI, added the control dom object to the **actionList**

            myReportLink = domConstruct.create("a",{
                "class": "action",
                "id": "statsLink",
                "innerHTML": "Parcel Report", //text that appears in the popup for the link
                "href": "javascript: void(0);"
            }, domQuery(".actionList", this.map.infoWindow.domNode)[0]);

and then call it in your way

on(myReportLink, "click", lang.hitch(this, 'parcelReportClick'));

seems since 3.31, there are quite bit change in the api, the style <a> somehow vanished in this widget. But anyway, just to let you know my work around. 


Thanks!

**Comment by tmcgee** [comment]
@ERS-Long Thanks for the alternative. I believe that action list code would add the link to the infoWindow for ALL features that are identified not just the specific layer with the desired report.

It appears to me that the ESRI code strips the ID attribute from the href. It might have to do with the HTML sanitation supposedly "fixed" in  [BUG-000133257](https://developers.arcgis.com/javascript/3/jshelp/whats_new.html). If so, it affects more than the Report widget. I will research further. Thanks again for the report
