### ISSUE TITLE
Export: Fields not visible in Excel when passing FeatureSet

### ISSUE THREAD

**Issue by gobsmack** [tmcgee/cmv-widgets#24]
When using the Export widget, passing a FeatureSet, I see that the fields are hidden in Excel. I say "hidden" because the Excel column headers don't start at A, they take into account the columns that were passed. I'm not sure if this is an existing bug, or specific to the FeatureSet. The code appears to be setting "hidden: false", so more investigation is needed.

**Comment by tmcgee** [comment]
@gobsmack Did you have any opportunity to investigate this?
