### ISSUE TITLE
How to get Featuredatsets from ARCSDE?

### ISSUE THREAD

**Issue by pnh10** [tmcgee/cmv-widgets#25]
list all the SDE datasets in one combobox
on change of that combo box we have to list all the featureclasses in that dataset in another combo box
on click of download we have to download that layer ?

**Comment by tmcgee** [comment]
Is this a request for a new widget?

**Comment by mondagu87** [comment]
Hi,
Yes....

rds,
Naveen

**Comment by pnh10** [comment]
Any Reference for further proceedings.....

**Comment by tmcgee** [comment]
Maybe this widget will get you what you want or get you started? https://github.com/tr3vorm/cmv-extract-widget

**Comment by pnh10** [comment]
How to connect  arc sde  oracle database to get datasets  in to combobox?...Pls provide any reference for further...
