### ISSUE TITLE
_GraphicsMixin bug

### ISSUE THREAD

**Issue by jebu75** [tmcgee/cmv-widgets#28]
In _GraphicsMixin on lines 289 and 290 there is no need for the PopupTemplate class.  I believe this is handled by the underlying map.

Removing line 289 and changing 290 as follows correctly displays the configured infoTemplate on the search result graphic:

```
graphic.setInfoTemplate(this.infoTemplate);
```

This has been tested successfully in one of my applications.

**Comment by tmcgee** [comment]
Thanks. The same change would need to be applied at lines 342 and 343 for the selected graphics.

**Comment by jebu75** [comment]
Good catch, will do!  I'll create a PR later today.

**Comment by tmcgee** [comment]
@jebu75 Is it "later today" yet? ;)

**Comment by tmcgee** [comment]
@jebu75 got a PR?
