### ISSUE TITLE
AttributesTable - Graphics for same query not displayed after closing tab

### ISSUE THREAD

**Issue by jebu75** [tmcgee/cmv-widgets#29]
I've tried tracking this one down but haven't had any luck.  I'm using the Search and AttributesTable widget together.  The first time I execute a search, graphics are displayed no problem.  Subsequent executions of the same search (with different values) also work just fine.  If however, I close the tab with the search results between searches, the graphics are no longer displayed.  Selecting a row will still zoom to the feature but the graphics, neither highlighted or selected are displayed.

Any ideas?

**Comment by tmcgee** [comment]
@jebu75 I can duplicate this behavior [here](http://tmcgee.github.io/cmv-widgets/demo.html?config=search).

Not looking at the flow of the code, here's 2 thoughts:
1. Perhaps the graphics layers are hidden and a call to the `showAllGraphics` method is needed after the tab re-added to make the graphic layers visible?
2. It is also possible we have a collision of the names for the graphics layers if `addGraphicsLayers` is being called again when the tab is re-added. That routine probably needs to look for an existing graphics layer in the map with the same name and use it instead of creating a new layer.

I lean more towards the second option.

**Comment by jebu75** [comment]
I tried tracing it out and I don't think the graphic layer gets recreated when a tab is re-opened.  If you inspect the featureGraphics layer in the addFeatureGraphic function, it's also visible and seems to be attached to the map.

Could it be related to declaring the layers and initializing to null outside the _GraphicsMixin constructor?  I seem to recall this could cause issues as all instances of the class would end up with a reference to the same value of the property..

I think I'll try moving these declarations inside the constructor so they are instance specific and post back.

**Comment by jebu75** [comment]
@tmcgee I believe you are correct about the 2nd possibility.  To fix you could:
a) search the map and re-use the layer if exists
b) remove the layer when a tab is closed and always create when a tab is opened

I think option a is easier but potential leaves unused layers in the map.  What do you think?

**Comment by tmcgee** [comment]
option a is easier - the current code already leaves the unused layers in the map if the tab is closed so adopting option a would not change that.

Leaving unused layers in the map is bad design on my part. Regardless of whether the tab ever gets re-opened, I think the layers should be removed when the tab is closed.

**Comment by jebu75** [comment]
The fix actually turned out to be pretty easy.  Created a removeGraphicsLayer in _GraphicsMixin method to remove each graphic layer from the map and set the reference to null.  Then implemented the destroy() which calls the removeGraphicsLayer method.  I put the method in Table as there might be other cleanup actions when a table gets removed but I think it could just as easily go in _GraphicsMixin and perhaps would be better there.

Seems to work though.  I can now execute multiple searches with the same topicID, whether spatial or attribute, closing the tab between executions and the graphics display.

Would like a PR submitted?

**Comment by jebu75** [comment]
```
//_GraphicsMixin.js
...
        /*******************************
         *  Remove Graphic Layers
         *******************************/
        removeGraphicLayers: function () {
            this.map.removeLayer( this.sourceGraphics );
            this.sourceGraphics = null;

            this.map.removeLayer( this.bufferGraphics );
            this.bufferGraphics = null;

            this.map.removeLayer( this.featureGraphics );
            this.featureGraphics = null;

            this.map.removeLayer( this.selectedGraphics );
            this.selectedGraphics = null;
        },

        destroy: function () {
            this.removeGraphicLayers();
            this.inherited( arguments );
        }
```

**Comment by tmcgee** [comment]
Yes, please and thank you. A PR would be most welcome!

Could/should `removeGraphicsLayers` be called from the `removeTab` method in AttributesTables.js right after the graphics are cleared? https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable.js#L192 I am wondering if that makes the code easier to follow instead in a separate `destroy` method.

**Comment by jebu75** [comment]
I sort of favor the destroy method, I like that the widget, or mixin, cleans up after itself but either approach I think is equatable.  However, it's your widget so I'll let you make the call.  Let me know which way you want to go and I'll work up a PR.

Thanks!

**Comment by tmcgee** [comment]
OK. I like the destroy method approach but shouldn't it be in Table.js not one of the mixins because the mixin never stands alone. The widget has a lifespan so it should get the destroy method.

I think then the destroy method would also call `this.clearAll()` and you can remove this if statement:             https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable.js#L191

**Comment by jebu75** [comment]
Sounds good, I agree, the destroy method should go be in Table.js.  That's where I originally had it.

Can this line also be removed (handles user closing tab _I think_)?
https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable.js#L163

**Comment by tmcgee** [comment]
Yes it can.

**Comment by tmcgee** [comment]
@jebu75 got a PR?

**Comment by tmcgee** [comment]
This has been added in an upcoming release.
