### ISSUE TITLE
Search Widget Question

### ISSUE THREAD

**Issue by kjmueller** [tmcgee/cmv-widgets#3]
Hi Tim,

When using the select 'By Shape' tab, how do I add more layers to the dropdown?

Thanks!

**Comment by tr3vorm** [comment]
They should just appear from the layers configured in `/js/config/search.js`
I only use `type: 'spatial'` in my configuration and all layers appear in both the attribute and the spatial searches.

**Comment by tmcgee** [comment]
As @tr3vorm said, you need to be sure to use `type: 'spatial'`. If use `type: 'table'`, it will not appear in the `By Shape` tab drop-down list..

**Comment by kjmueller** [comment]
Thanks for both responses!  I tried to add an additional spatial search on top of the damage assessment one but with no luck.  I still very new to JS so any additional guidance as to where I may be going wrong would be greatly appreciated!  Below is the only modification that I made to the code.  Thanks again for the help!

layers: [

```
         {
            name: 'louisvillePubSafety',
            expression: '', // additional where expression applied to all queries
            idProperty: 'objectid',
            queryParameters: {
                type: 'spatial', // spatial, relationship, table or database
                layerID: 'louisvillePubSafety', // from operational layers
                sublayerID: 0,
                outFields: ['*']
            },


            name: 'Damage Assessment',
            expression: '', // additional where expression applied to all queries
            idProperty: 'objectid',
            queryParameters: {
                type: 'spatial', // spatial, relationship, table or database
                layerID: 'DamageAssessment', // from operational layers
                sublayerID: 0,
                outFields: ['*']
            },
```

**Comment by tr3vorm** [comment]
I would go back and download the original search.js for comparison. The `attributeSearch` section is required for the spatial search too. There is no such thing as "spatial only search" at this stage.

**Comment by kjmueller** [comment]
Got it working.  Thank you

**Comment by drusexton** [comment]
@kjmueller @tmcgee @tr3vorm 

Has anyone determined how to implement the spatial search without the attributes dependency yet?

**Comment by tmcgee** [comment]
@drusexton If you mean show only the spatial tab, see my response [here](https://github.com/cmv/cmv-app/issues/731#issuecomment-312599386)

**Comment by drusexton** [comment]
@tmcgee I was rather vague in my question, so I apologize. I will move this to a new issue.
