### ISSUE TITLE
Attachment links in the table

### ISSUE THREAD

**Issue by goriliukasbuxton** [tmcgee/cmv-widgets#30]
Hello,
was interested in adding column with attachment links in the attribute table. Wonder is it possible to achieve this?

Thank you,

**Comment by tmcgee** [comment]
@goriliukasbuxton This is definitely possible - the only barrier to success might be dependent on your data. There are multiple ways to formulate the hyperlink(s) html. Several of them listed below are relatively easy to use. You can add them within the column definition in the attributes tables config or the search config. You are really interacting with the dgrid so here's the [docs for dgrid](https://github.com/SitePen/dgrid/tree/v0.4.0/doc)

You can use the `get` method to change the value as it is retrieved from the record for use in the grid. Here's [an example that changes a date to a "real" date](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L61) which is helpful when exporting to excel.

Another approach is to use the `renderCell` method to change what is displayed in the grid. Here's a [somewhat complicated example](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget-relatedRecords.js#L62) that does more than you probably need but is a good one to keep in mind for later. That one handles clicking the entire cell to show run a query for related records. I don't have a working public example for you to see.

For your purposes, the best might be to use the 'formatter` method. With formatter, it is as simple as doing something like this:

``` javascript
formatter: function (value) {
    return '<a href="' + value + '" target="_blank">Open Attachment</a>';
}
```

If you have multiple hyperlinks per record all within a single field, the approach would be slightly different.

Perhaps this is more than you wanted :) I feel it is good to be aware of all of the options and it is now documented for others to find as well. Hope this helps.

**Comment by goriliukasbuxton** [comment]
Thank you,
I will investigate the config's. Not sure about the multiple features for each item.

**Comment by goriliukasbuxton** [comment]
Search not showing the dropdown:
//////////////////////////////
define([
    'dojo/on',
    'dojo/date/locale'
], function (on, locale) {

```
function formatDateTime (value) {
    var date = new Date(value);
    return locale.format(date, {
        formatLength: 'short'
    });
}

return {
    map: true,
    mapClickMode: true,

    layers: [
        {
            name: 'Lease Blocks',
            expression: '', // additional where expression applied to all queries
            idProperty: 'OBJECTID',
            queryParameters: {
                type: 'table', // spatial, relationship, table or database
                layerID: 'boundary', // from operational layers
                sublayerID: 15,
                outFields: ['*']
            },

            attributeSearches: [
                {
                    name: 'Lese Blocks',
                    searchFields: [
                        {
                            name: 'Lease Blocks',
                            label: 'Blocks',
                            expression: '(LEASE_NUMBER = [value])',
                            placeholder: 'Enter the Number',
                            required: true

                        }
                    ],

                    title: 'Lease Block',
                    topicID: 'policeStationQuery',
                    gridOptions: {
                        columns: [
                            {
                                field: 'LEASE_NUMBER',
                                label: 'Name',
                                width: 150
                            }

                        ],
                        sort: [
                            {
                                attribute: 'LEASE_NUMBER',
                                descending: 'ASC'
                            }
                        ]

                    }
                }
            ]
        }

    ]
};
```

});

**Comment by tmcgee** [comment]
This isn't related to the original question so hopefully we don't go too far out on this tangent.

I don't see anything syntactically wrong with this. A couple of things:
1. I assume you have a layer in your operational layers with an id of `boundary`?
2. You have `type:'table'` but this is presumably a layer since you have a layer id. What happens if you switch to `type: 'spatial'`? Only `spatial` will show up in both the drop down lists. `table` will not show up on the 'By Shape' tab since you can't search spatially for non-spatial data.

**Comment by goriliukasbuxton** [comment]
operation layer:
{
                type: 'dynamic',
                url: 'http://gis.boemre.gov/arcgis/rest/services/BOEM_BSEE/MMC_Layers/MapServer',
                title: 'Boundary',
                options: {
                    id: 'boundary',
                    opacity: 1.0,
                    visible: false,
                    outFields: ['*']
                },
                layerControlLayerInfos: {
                    swipe: true,
                    metadataUrl: false
                }
            }

SearchWidget changed type to the 'spatial'still no dropdown.

**Comment by tmcgee** [comment]
Assuming you were using the latest version, this probably is my bad. There was an update a couple of days that had an incorrect ending for a comment block. This resulted in 90% of the Search widget code being commented out. Oops. Not sure how I missed that one!

I just fixed it, so you can download a new copy of the widget(s) and then you should be fine. I tested and verified it works using your configurations for operational layer and search widget.

**Comment by goriliukasbuxton** [comment]
OK. I knew something was up, because i had it configured before.
Thank you,
I am sure i will have more question about the relational queries.

**Comment by goriliukasbuxton** [comment]
I was wondering how to query attachements from the cell.
Should i use the "layer.queryAttachmentInfos"? or has to be thru relational table call like in the https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L61
?

**Comment by tmcgee** [comment]
If you need to do that kind of separate request to get multiple attachments, you might want to follow the approach that @carrbrpoa did here: https://github.com/cmv/cmv-app/issues/452. His original issue was #26.

**Comment by tmcgee** [comment]
You might want to wrap the call to `queryAttachmentInfos` with a check of `layer.hasAttachments` to see that there are actual attachments to get. That will save time.

**Comment by goriliukasbuxton** [comment]
Not sure how to get the map and layer object referenced in the searchWidget.js, so i could use the queyAttachmentInfos method.

**Comment by goriliukasbuxton** [comment]
Does relational table can be non-spatial table? I am using this as example:
https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget-relatedRecords.js

**Comment by goriliukasbuxton** [comment]
Used this simple example to open attachments:

renderCell: function (object, value, node) {
                                        on(node, 'click', function ()
                                            var layer = new FeatureLayer('yourserver_featureservice');
                                            layer.queryAttachmentInfos(value, function (infos) {
                                                        window.open(infos[0].url);
                                                    });  
                                        });
node.innerHTML = '<i class=\'fa fa-pencil\' style=\'margin-left:8px;\'></i>';  
                                    }

**Comment by tmcgee** [comment]
@goriliukasbuxton that's a real good answer for a single attachment. If not all your features have attachments, you might want to use `hasAttachments` to verify that there is an atttachment to open  

When there are more than one, I can envision formatting a list of hyperlinks and opening a popup window to show those as clickable hyperlinks or populating a new attributes table with all the hyperlinks.

**Comment by goriliukasbuxton** [comment]
Could it be a grid with attachment link's inside the cell?

**Comment by carrbrpoa** [comment]
Yes @goriliukasbuxton, one option is to build `<a>` elements with the URLs you need and increment `node.innerHTML`. Something like this:

``` javascript
var nodeContents = '';
array.forEach(infos, function (info, i) {
    nodeContents += '<a href="' + info.url + '" target="_blank">Attachment</a> ';
});

node.innerHTML = nodeContents;
```

If you want a new table instead, you may want to work with something like

``` javascript
...
on(node, 'click', function () {
    topic.publish('attributesContainer/addTable', {
    ...
```

**Comment by goriliukasbuxton** [comment]
Thank you @carrbrpoa.  I will try it out.
@tmcgee  I am having trouble with the configuring the query relation table using this example from searchWidget-relatedRecords.js.
where does the origin relational id field goes and where destination relational id field goes?
Thank you.

**Comment by tmcgee** [comment]
@goriliukasbuxton that query is intended to be used if you have relationship classes within your ArcGIS Server. Relationship Classes provide and maintain the relationshipID for the various related tables/records in your AGS.

**Comment by goriliukasbuxton** [comment]
OK. I do have AGS relationship class. Origin id field is "Item", and the destination id field is "REL_ID", relationship number is is "0".
Thank you,

**Comment by goriliukasbuxton** [comment]
Got it to work.
Thank you all for awesome code and suggestion.

**Comment by tmcgee** [comment]
excellent!

**Comment by goriliukasbuxton** [comment]
I wonder how to check to see if row in the table has the related records before its renders, my try here:
https://gist.github.com/goriliukasbuxton/4a8c7a1687a57d640dd2

**Comment by tmcgee** [comment]
@goriliukasbuxton please create a new issue for this.

**Comment by goriliukasbuxton** [comment]
@carrbrpoa,
I would to create a click event (sends a link id) for each link, my try here:
https://gist.github.com/goriliukasbuxton/2ec1af4a73ff3f5eb495
