### ISSUE TITLE
Query related  records before render cell

### ISSUE THREAD

**Issue by goriliukasbuxton** [tmcgee/cmv-widgets#32]
I wonder how to check to see if row in the table has the related records before its renders, my try here:
https://gist.github.com/goriliukasbuxton/4a8c7a1687a57d640dd2

**Comment by tmcgee** [comment]
@goriliukasbuxton you might try something like this: https://github.com/cmv/cmv-app/issues/452#issuecomment-135864893

Essentially, that example provided by carrbrpoa sets the value of an attribute field after getting the value from an external call. You could do the same thing setting the total number of related records. Then your renderCell function would simply use that value to determine if a link should be shown or not. You could also display the number of related records (from the new attribute) to give the user additional feedback.

**Comment by goriliukasbuxton** [comment]
Will do, Thank you
