### ISSUE TITLE
_GraphicsMixin  unhighlightGraphic not firing in IE

### ISSUE THREAD

**Issue by kcsgisRham** [tmcgee/cmv-widgets#33]
The highlighted graphics from a search are not being unhighlighted in IE 10 and 11 on Windows 7, 8 and 10 and also in the new Microsoft Edge.Line 239 adds the mouse-out event to the graphics, but the  unhighlightGraphic function never fires in IE on line 517.

**Comment by tmcgee** [comment]
That @kcsgisRham This is a known issue with Internet Explorer.

**Comment by kcsgisRham** [comment]
@tmcgee, thanks for the heads up.
