### ISSUE TITLE
Reload Table

### ISSUE THREAD

**Issue by gisgeo** [tmcgee/cmv-widgets#35]
Hello everyone, I want to know if there's a way to reload an attribute table, I am using a query and the results are displayed in the table in the beginning, and I gave the user the ability to select some features then delete them. What I want to do is a "refresh or reload" to the table after the delete is complete. is it possible?

**Comment by gisgeo** [comment]
I found a way to achieve what I wasl looking for, if anyone needs this in the future here's what I did: I used a function refresh in the "_QueryMixin.js":
                refresh; function()
               {
                        this.executeQuery(this.queryOptions);
               }

**Comment by tmcgee** [comment]
Thanks @gisgeo I think this is a nice addition as it has been requested a few times.
