### ISSUE TITLE
No data displayed in the grid when pagination is false

### ISSUE THREAD

**Issue by darinatch** [tmcgee/cmv-widgets#36]
I am not sure why, but if I set pagination to false in the grid options, the grid displays only a header and the data rows are missing. 

Has anybody encountered this and found the solution?

Thank you!

**Comment by tmcgee** [comment]
@darnatch I have not heard of this issue. I will look into it.

**Comment by tmcgee** [comment]
@darinatch I have duplicated your issue with `pagination: false` and am working on a solution.
