### ISSUE TITLE
Extra node next to grid node

### ISSUE THREAD

**Issue by goriliukasbuxton** [tmcgee/cmv-widgets#37]
Hello,
I was wondering how to add extra node next to your grid node,
On click user would view attachments  in that node

Thank you,

**Comment by tmcgee** [comment]
@goriliukasbuxton what do you mean by "add extra node"? Are you looking for an additional tab in the bottom pane that would have a new grid listing attachments associated with a record in the first grid? Or are you looking for a window where they would view the actual attachment (like PDF document)?

**Comment by goriliukasbuxton** [comment]
Looking for a window next to the grid to see the attachment then the link button is clicked.

Thank you,

**Comment by tmcgee** [comment]
Sounds like a custom widget which can be used by an Attribute Tables grid or from the Identify's infoWindow. I am not aware of an existing widget that does this.

**Comment by goriliukasbuxton** [comment]
Got something going with:
content: '<div id="attributesContainer" style="width:65%;float:left"></div><iframe id="doclink" src="" style="height:100%;width:34%"></iframe>'
the in searchWidget.js:
add references to the:
'dojo/dom', "dojo/dom-attr"
add rederCell:
renderCell: function (object, value, node) {
                                        on(node, 'click', function () {  
                                            var layer = new FeatureLayer('server_url')
                                            layer.queryAttachmentInfos(value, function (infos) {                                                domAttr.set(dom.byId("doclink"), "src", infos[0].url);
                                                    });
                                        });
                                        node.innerHTML = '<i class=\'fa fa-pencil\' style=\'margin-left:8px;\'></i>';
                                    }

**Comment by tmcgee** [comment]
@goriliukasbuxton I think some of your code (html perhaps?) got lost in that post.

**Comment by goriliukasbuxton** [comment]
Gist version:
https://gist.github.com/goriliukasbuxton/736e4e088d7166879e0a

**Comment by goriliukasbuxton** [comment]
@tmcgee how is the export widget is incorporated into the attribute widget?
thinking about the adding widget as attachments viewer.
Thanks,

**Comment by tmcgee** [comment]
1. The export widget is included in the viewer.js: https://github.com/tmcgee/cmv-widgets/blob/master/config/search.js#L121
2. By default, the `floating` widget type does not open at startup so the Export dialog is hidden.
3. When the toolbar button is clicked, it publishs a topic: https://github.com/tmcgee/cmv-widgets/blob/master/widgets/AttributesTable/_ToolbarMixin.js#L147
4. The subscribed topic calls this function to initialize and then show the Export dialog: https://github.com/tmcgee/cmv-widgets/blob/master/widgets/Export.js#L128
