### ISSUE TITLE
Attribute Table widget: Link the widget's graphics visibility with Layers in the Layer Control's visibility

### ISSUE THREAD

**Issue by gisgeo** [tmcgee/cmv-widgets#38]
Did anyone link the visibility of an attribute table's graphics with its corresponding layer from the Layer Control? This means that when the layer is not visible the attribute table's graphics should be hidden and so on. If not can you please guide me to the proper direction. 
I am working on this and I think it would be a great adittion, I will come back here if I find anything.

**Comment by tmcgee** [comment]
I prefer to not directly tie the functionality of one widget to that of another in case the functionality of one of the widget changes. You might want to approach this by responding to the visibility of the corresponding layer in the map using the [`visibility-change` event](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#event-visibility-change) and then publishing a topic that your Attrbutes Table is subscribed to like `topic.publish('attributesTable/showAllGraphics')` and `topic.publish('attributesTable/hideAllGraphics')`. 

You can do all this in your own `invisible` widget without any changes to the Attributes Table widget. If you choose to add this type of code directly to the Attributes Table widget in a way that is configurable and thus optional for others to use or not, please submit a PR.
