### ISSUE TITLE
Are you able to just show that dialogur one time or with a button remember my answer?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#40]
Thanks TIM
Great job again... do you thing it will be good to put an other button like Remember my answer
 To do not display the disclaimer the next time or its to complex...
![timdisclamer](https://cloud.githubusercontent.com/assets/6784515/10075658/df2415a8-62a4-11e5-9309-0286a6b7495e.jpg)

**Comment by tmcgee** [comment]
Thanks @GilbertLasnier Currently, that functionality does not exist. It is on the list for future enhancements.

**Comment by GilbertLasnier** [comment]
Hello Tim

 I turn off the disclaimer because on the IPAD you must click the accept button almost with an hammer before its working!!!
What do you think its seam incompatible with the IPAD…

**Comment by tmcgee** [comment]
I do not have an iPad for testing. It works without issue on Android. I'll look into also responding to the touch event in addition to the click event.

**Comment by GilbertLasnier** [comment]
There is no dialogue... its work after you hit the accept very strong many times... No body I think must succeed.... me its because I know its supposed to work so ...I hit the accept button with my finger until its working its take almost 10-20 hard touch...

**Comment by tmcgee** [comment]
It sounds like you think I said your site works with Android. I did not test that. What I meant was that the code in the disclaimer widget works with Android.

**Comment by GilbertLasnier** [comment]
I don't test on android here everybody receive a iPad

**Comment by tmcgee** [comment]
The original functionality requested has been added in [this commit](https://github.com/tmcgee/cmv-widgets/commit/81c033cf3cd79c155b349e0515b639fed796efa3). The new configurable options are documented in the disclaimer widget's [README](https://github.com/tmcgee/cmv-widgets/tree/master/widgets/Disclaimer).

**Comment by GilbertLasnier** [comment]
Thanks Tim a retry with what you change…
