### ISSUE TITLE
About the arguments in the Share Map widget (zoom lat long missing)?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#41]
I try this morning the share this map…
In my mind I think when you zoom the widget retain the zoom IN THE LINK???
EXAMPLE: embed map don't retain the zoom

<iframe width='100%' height='640px' src='http://gis.icao.int/icaoviewernew/?extent=-84.825439,25.102866,-78.272095,28.649480' frameborder='0' scrolling='no'></iframe>

When you zoom to the Floride…
http://gis.icao.int/icaoviewernew/?extent=-83.199463,25.807166,-79.922791,27.583622#/-81.5433/26.8901/8
It will be very great that the link is able to retain the Zoom
Many thanks to you

**Comment by tmcgee** [comment]
@GilbertLasnier 

You have 2 sets of coordinates in that link that appear to be for 2 widgets that are incompatible with each other. Obviously, the extent is from the share widget. What is the other widget that adds the center point + zoom level as that is not part of CMV. I think the way that second widget adds the coordinates to the url including a leading slash may be done incorrectly when the url has a query string on it (the extent)

You can always prevent the user from adding the extent onto the shared link by hiding the proper Div element via CSS so they cannot click that check box.
