### ISSUE TITLE
Unable to Export the map with arc server 10.2

### ISSUE THREAD

**Issue by pnh10** [tmcgee/cmv-widgets#46]
On Print button click unable to print the Map ...Eventhough  print tool  Url created in 10.2 unable to Print the map..It is showing the error as "Error ,Try again"

**Comment by tmcgee** [comment]
@pnh10 That error usually indicates a problem generated by the server's print task. Can you print the same map/extent/layers using the core CMV Print widget? This will help identify if it is a problem specific to this custom widget or to printing in general.

**Comment by pnh10** [comment]
With the help of Core Cmv print widget also we cant print the map/extent /layers....If the service is access with internet then Only we can able to print ...

**Comment by pnh10** [comment]
Hi

can i have customization in "Near Me" widget where i need to have layerlist items (ex 10 layers) with on/off mode so that i can select the layers and can get the nearest features from the mentioned point

**Comment by tmcgee** [comment]
@pnh10 Neither of the near me widgets (there are at least 2) were created by me. You should start by asking the author of the widget for this customization in the proper repository.
