### ISSUE TITLE
Zoom To Feature Multiple Dropdowns

### ISSUE THREAD

**Issue by kcarrier** [tmcgee/cmv-widgets#49]
@tmcgee - What is the best way to implement multiple drop downs.

Should I create different versions of the same widgets or if there a way to specify multiple drop down downs within the same widget?

**Comment by tmcgee** [comment]
I think this would most easily be accomplished with different instances of the same widget (each with a separate url, field).

If you use a widget `type: 'titlePane'`, each widget will be in a separate title pane widget in the sidebar. Instead, you might be able to use a widget type of `contentPane` or `'domNode` to place the multiple dropdowns within the same container.

**Comment by kcarrier** [comment]
@tmcgee - Thank you sir let me work on this and if I get something working I will post back with the working code.

**Comment by kcarrier** [comment]
@tmcgee - I have tried changing to contentPane and domNode although I could not find any examples of contentPane. I think I saw domNode hooked to some buttons like the locateButton, not sure how to accomplish this with a widget. It would be neat if something like this could be accomplished, possibly a future enhancement opportunity as Esri likes to tell me :). Thanks again for all the help, for now separate widgets will work. Here is how I accomplished this.

```
            zoomToFeature: {
                include: true,
                id: 'zoomToFeature',
                type: 'titlePane',
                title: 'School Zones',
                position: 0,
                open: false,
                path: 'gis/dijit/ZoomToFeature',
                options: {
                        map: true,
                        url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Query_Service_150605/MapServer/5',
                        field: 'NAME',
                        where: '1=1',
                        // you can customize the text
                        i18n: {
                            selectFeature: 'Select A School Zone'
                        } 
                }
            },
            zoomToFeature2: {
                include: true,
                id: 'zoomToFeature2',
                type: 'titlePane',
                title: 'Charter Schools',
                position: 0,
                open: false,
                path: 'gis/dijit/ZoomToFeature',
                options: {
                    map: true,
                    url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Query_Service_150605/MapServer/0',
                    field: 'NAME',
                    where: '1=1',
                    // you can customize the text
                    i18n: {
                        selectFeature: 'Select A Charter School'
                    }
                }
            },
            zoomToFeature3: {
                include: true,
                id: 'zoomToFeature3',
                type: 'titlePane',
                title: 'Magnet Schools',
                position: 0,
                open: false,
                path: 'gis/dijit/ZoomToFeature',
                options: {
                    map: true,
                    url: 'http://67.154.191.149:6080/arcgis/rest/services/Charleston/Charleston_Query_Service_150605/MapServer/1',
                    field: 'NAME',
                    where: '1=1',
                    // you can customize the text
                    i18n: {
                        selectFeature: 'Select A Magnet School'
                    }
                }
            },
```

**Comment by tmcgee** [comment]
@kcarrier I've added an example configuration to show how multiple zoomToFeature widgets can be placed in a single titlePane widget. The configuration file is [here](https://github.com/tmcgee/cmv-widgets/blob/master/config/zoomToFeature-multiple.js). You can see it in action [here](http://tmcgee.github.io/cmv-widgets/demo.html?config=zoomToFeature-multiple).

**Comment by kcarrier** [comment]
@tmcgee - I have said it more than a few times and I will say it again, you da man!
