### ISSUE TITLE
Export issue in IE 11

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-widgets#53]
Hi, Tim:

Seems the export button does not work in IE 11, i tried your export widget example using IE

11.0.9600.18163

It works beautifully in Chrome, FireFox. 

We have this one client that are somehow glued to IE.  

Do you think there is a way to resolve this? 

Thanks

**Comment by tmcgee** [comment]
The current version of export does work in IE 11. I just tested to verify. Is it possible this the same client that we discussed earlier this week that is using an old version of the widgets?

**Comment by ERS-Long** [comment]
Good point, i will give it a try. But i tried your export example, got the same issue. Do you think it could be our IE, is there anything we can check?

**Comment by ERS-Long** [comment]
Hi, Tim: Do you think it is permission related? when i check my IE setting, in the security tab, the current user only has Read & Execute permission. But if for chrome.exe, it has full permission. Do you think that might be the reason?

**Comment by tmcgee** [comment]
I have a number of clients using IE 11 and lower and can export. This could be security settings probably imposed by the It department. I've seen similar behavior in the past but not with CMV. Sorry I don't more to add.

**Comment by ERS-Long** [comment]
Thanks, I will try this using my home computer tonight. If it works, then it must be the IE settings in our office.

**Comment by tmcgee** [comment]
@ERS-Long Did you get the Export to work in IE 11?

**Comment by ERS-Long** [comment]
No, sir.

Still looking.

Thanks

**Comment by tmcgee** [comment]
Did it work from your home computer?

**Comment by ERS-Long** [comment]
Not working either, my home computer is running win 8 64 bit, i am not sure does that make any difference. The issue is i tried your export example, but i cannot open in ie at all.

Seems like i will go to the dev summit next week, i will see you guys, i missed it for last year's one, but i was there, just did get the meeting msg for cmv.

Thanks.

**Comment by ERS-Long** [comment]
Hi, Tim: tried this morning again, still no luck.

Here is the error captured from IE 

Unable to get property 'WBProps' of undefined or null reference.

Anyway, hopefully i can show this to you next week and see if you can help me to figure that out.

Thanks

**Comment by ERS-Long** [comment]
Thanks Tim, it was a very good meeting for the CMV project status. I cannot wait to see the 3D enabled CMV code.

Here is the IE 11 export error. 

it errors out on file called xlsx.core.min.js, the actual error is 

 'Unable to get property 'WBProps' of undefined or null reference'

Thanks a lot

**Comment by tmcgee** [comment]
@ERS-Long Great to meet you last week.

I still have not been able to replicate the issue. The error is coming from the xlsx.core library which is not mine to support or troubleshoot. Another version of the library might fix it but since I can't replicate, I won't know.

There is another alternative that might help you. A new export option was added in PR #51 to export as XLS in addition to XLSX. It does not use any external libraries. In that PR there was a small bug which I just fixed. Try the XLS export. If that works, you can disable the XSLX export and offer only XLS. Let me know how it goes.

**Comment by ERS-Long** [comment]
Thank you very much, Sir. 

It is working in IE 11 now after i applied your merged version of export code.

I really appreciated your help.

**Comment by ERS-Long** [comment]
Hi, @tmcgee:

Got another question related to Export widget, how to use it in my own grid, for example, i have a data grid, just want to export the grid data to csv or excel, my solution only works in Chrome, so since your merged code resolved the ie 11 attributes export issue, so i am hoping i can use the same code for my own grid data. Please let me know what steps i need to take. Thanks

Here is my current export code:

```
        var csvContent = "data:text/csv;charset=utf-8,";

        console.log(arrayData);
        arrayData.forEach(function(dataMember, index)
        {
            dataString = dataMember.join(",");
            csvContent += index < arrayData.length ? dataString+ "\n" : dataString;
        }); 

        var encodedUri = encodeURI(csvContent);
        var link = document.createElement("a");
        link.setAttribute("href", encodedUri);
        link.setAttribute("download", "Export_Data" + (new Date()).getTime() + ".csv");
        link.click();
```

As always, thanks a lot first!

**Comment by tmcgee** [comment]
So does export to XLSX work or only XLS?

Try using the [`downloadFile`](https://github.com/tmcgee/cmv-widgets/blob/master/widgets/Export.js#L548) method in the Export widget since that works for all modern browsers.

**Comment by ERS-Long** [comment]
@tmcgee 

works for both.

So i can just use that downloadFile method for my own grid data, right? i will try that out, will report back. 

Thanks a lot

**Comment by tmcgee** [comment]
sounds like the problem was you didn't have the latest code. The only change I made recently was fixing the option to allow for XLS export. That explains why I could not duplicate it.

yes on using that method for downloading.

**Comment by ERS-Long** [comment]
Thanks a lot, Tim.

Got my grid data export working in IE 11 too, Very nice solution, all I have to do is 

// convert my array data, then call the downloadFile function

```
        var csv = arrayData.map(function(d){
            return d.join();
        }).join('\n');

        this.downloadFile(csv, 'text/csv;charset=utf-8;', this.getFileName('.csv'), true);
```

Thanks a lot, we can close this issue.
