### ISSUE TITLE
Duplicated Search Demo not working

### ISSUE THREAD

**Issue by JhopStl** [tmcgee/cmv-widgets#54]
Hey Tim, 

I've been having issues getting this widget working when trying to replicate your demo of the Search Widget on my end.  I can get the widget to pull up on the side panel, but there are not contents.  I doubt I'm providing enough information on the issue, but do you have any idea on what could be causing the errors (see the attached snip).
![search](https://cloud.githubusercontent.com/assets/16945459/13932241/252a5280-ef75-11e5-9dff-01246b460f17.JPG)

Thanks for your time,

Jesse

**Comment by tmcgee** [comment]
@JhopStl Sorry, I don't recall if this was resolved in the Gitter chat room or not. If this is still an issue, please let me know. If you have more details, let me know that too.

**Comment by JhopStl** [comment]
Tim,

Looks like it's still an issue.  I have put this aside for the time being, but will gladly come back to the issue in order to get it resolved.  I'm still pretty much a novice at js/dojo, so it's been hit or miss when it comes to debugging and troubleshooting the errors on my end.  

Here's the setup.  I added the Search widget to my existing CNV site but could not get it work properly (Started to pull my hair out)  So to make it a little easier, I made a new CMV site with just the search widget - pretty much identical to what you have as your "CMV Search Example", but I continue to get an error on line 690 of Search.js: "Uncaught TypeError: 'Cannot read property 'domNode' of undefined".  The details of this error are in the attached jpg in the above message.  

Let me know if you need better clarification of the issue.

Thanks,

Jesse

**Comment by tmcgee** [comment]
@JhopStl There was no jpg attached to your comment.

And to be sure we're talking about the same line 690, can you use the latest [version 1.6.0](https://github.com/tmcgee/cmv-widgets/releases/tag/v1.6.0) if you aren't already. Thanks.

**Comment by JhopStl** [comment]
Alright , I'll give the latest version a shot and let you know if that helps.
And here's the image/attachment I was referring to:

![252a5280-ef75-11e5-9dff-01246b460f17](https://cloud.githubusercontent.com/assets/16945459/14290086/42a7671c-fb23-11e5-95f8-920aa10762e8.JPG)

Thanks,

Jesse

**Comment by JhopStl** [comment]
Tim,

I was able to get the widget working after I changed/fixed a couple widget paths in my folder structure.  Thanks!
