### ISSUE TITLE
Just try to use your zoomToFeature, some questions?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#55]
Hello Tim
I just modified in the config/ zoomtofeature like that:
widgets: {
            zoomToFeature: {
                include: true,
                id: 'zoomToFeature',
                type: 'titlePane',
                title: 'Zoom to A California County',
                position: 0,
                open: true,
                path: 'widgets/ZoomToFeature',
                options: {
                    map: true,
                    // you can customize the button text
                    i18n: {
                        selectFeature: "Select A County"
                    },
                    url: 'http://gis.icao.int/ArcGIS/rest/services/5lnc2016/MapServer/2',
                    field: 'NAME_CODE',
                    where: '1=1',
                }
            }
        }
    };
First question:the drop down appear but do not zoom?? what is wrong?
Second: where is the viewer.js in multiple line, like old example?
with software you use to convert one line to multiple line to insert all your modification in one viewer.js CMV...
How to put new layers in your super app?

Third: I don t understood  your example: where: 'STATE_FIPS = \'06\' ',
where: 'Dist_NM <  \'761\' ', i just want when the field Dist_NM is less than 761NM I DONT UNDERSTAND THE \'    \ ' '?
I am working to included all your stuff in the CMV
 i have on line; your search and the table attribute you developed
there is the zoom to screen shot: the drop down work but when you select an element the zoom function is not working...:
![timzoomto](https://cloud.githubusercontent.com/assets/6784515/14209897/784324ce-f7f4-11e5-8eae-9569c12131e8.jpg)
Thank for your great support you do for me...

**Comment by tmcgee** [comment]
@GilbertLasnier 
1. The widget won't zoom to any of the features because your map service does not provide the geometry for that layer. Usually this is because the shape field is omitted from the attributes when the service is published.
2. You can include any widget in your `viewer.js`. In my repo, I have separate configuration files like `zoomtofeature.js` only as examples.
3. Using `\'` is necessary in JavaScript to "escape" the single quotes that are within the text so they are not confused with the single quotes that start and end the text. For a little more detail on the approach, look at the discussion of "Special Characters" here: http://www.w3schools.com/js/js_strings.asp

**Comment by GilbertLasnier** [comment]
TIM
Thanks I try all that Merci beaucoup!!!

**Comment by GilbertLasnier** [comment]
TIM your  good its working take a look on the **screenshot**...I show one line and one points it just missing an other point! 
I just want to know if its possible to zoom on duplicate points...
I have a lot of duplicates points and i want use your drop down function to show the duplicates, we are near...there is two PISUL, want to show both ...
Do you think its possible...
![timzoomdup](https://cloud.githubusercontent.com/assets/6784515/14217642/4b0626d6-f81d-11e5-8d40-42dc2c2eef2a.jpg)
Thanks again for your fast answer!

**Comment by tmcgee** [comment]
@GilbertLasnier That is not part of this widget. It just lists all the features it receives from the layer in the Map Service. A work around might be to create a layer that has an series of extents - each  encompassing all the points in common.

**Comment by GilbertLasnier** [comment]
Thanks I try that!

**Comment by GilbertLasnier** [comment]
What is a multiple point, Do you think I must use that to zoom; two same name point?

**Comment by tmcgee** [comment]
I don't understand your question about multiple point.

**Comment by GilbertLasnier** [comment]
Your zoom feature work perfectly…the question is I read about shape file point and shape file mujltipoint I don't know its existing???

**Comment by GilbertLasnier** [comment]
I found that on the internet (I'm trying to find a multipoint shapefile) maybe you know that??? and tell me, if its will be a solution for my Duplicates before I make the extent like you tell me.

**Comment by tmcgee** [comment]
Sorry, I do not know if the ZoomToFeatures widget will work with multi-point data.

The widget would work if you create data that has a single simple polygon (an extent) which includes all the points with the same name. I have several clients that have taken this route.
