### ISSUE TITLE
How to integrate the homeButton in your cmv-widgets-master you do?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#56]
Wonderful your Search with Attribute and Shape work...great!
[http://gis.icao.int/cmv-widgets-master/demo.html?config=search2]

I try now to install the homeButton
homeButton: {
                include: true,
                id: 'homeButton',
                type: 'domNode',
                path: 'esri/dijit/HomeButton',
                srcNodeRef: 'homeButton',
                options: {
                    map: true,
                    extent: new Extent({
                        xmin: -180,
                        ymin: -85,
                        xmax: 180,
                        ymax: 85,
                        spatialReference: {
                            wkid: 4326
                        }
                    })
                }
            },
I copy that in the search2
and nothing work I try many things... no success ...
Do you have an idea?
Thanks again for your great tools
![timtool](https://cloud.githubusercontent.com/assets/6784515/14565952/77f7c936-02fb-11e6-9fd5-b21710982ea9.jpg)

**Comment by tmcgee** [comment]
@GilbertLasnier I looked at the link you provided. There is no home button in the `search2.js` configuration file for that application. There are no tricks to adding that widget. Perhaps you are adding it to a different application?

**Comment by GilbertLasnier** [comment]
I know There is no home button in the search2.js configuration file because when I put in the search2.js he crash …But
There are no tricks to adding that widget??? Its in all CMV but not in your super cmv-widgets-master, I don't understood!!!

**Comment by tmcgee** [comment]
You can copy the home button configuration from one application and paste into another. I suspect you pasted the code in the wrong place and that caused the configuration to have errors. What the error was I cannot say because the home page widget configuration is not in the file.

**Comment by GilbertLasnier** [comment]
I just copy the code          homeButton: {
                include: true,
                id: 'homeButton',
                type: 'domNode',
                path: 'esri/dijit/HomeButton',
                srcNodeRef: 'homeButton',
                options: {
                    map: true,
                    extent: new Extent({
                        xmin: -180,
                        ymin: -85,
                        xmax: 180,
                        ymax: 85,
                        spatialReference: {
                            wkid: 4326
                        }
                    })
                }

```
                                         },
```

In the searck2.js
Just try that in your own code and tell me if you succed to obain the Home button?

**Comment by tmcgee** [comment]
I have used the search widget and the home page widget in dozens of applications. I suspect but cannot say for sure that you may have forgotten to include the esri "Extent" module. The configuration file that you copied your code from will have that at the top of the file. You can also exclude the `extent` property if you don't need that.

**Comment by GilbertLasnier** [comment]
ALLO TIM,
I KNOW MY ENGLISH IS BAD, YOU SEARCH WIDGET WORK PERFECTLY… I JUST WANT PUT THE HOMEBUTTON IN THE: CONFIG/SEARCH2.JS
I MAKE ALL MY CHANGE THERE AND ITS WORK PERFECTLY; I am JUST MISSING THE HOMEBUTTON,
http://gis.icao.int/cmv-widgets-master/demo.html?config=search2

Try on your side to insert the Home Button in one of your example I am sure you succeed…I go for lunch now…
Thank to you…
Gilbert

**Comment by tmcgee** [comment]
@GilbertLasnier It certainly can be a challenge because of the different languages. I am doing my best to understand and assist. I wish I could converse in French and a number of other languages. :)

My previous message suggested adding the home button widget without the extent. It would look like this:

```
homeButton: {
    include: true,
    id: 'homeButton',
    type: 'domNode',
    path: 'esri/dijit/HomeButton',
    srcNodeRef: 'homeButton',
    options: {
        map: true
    }
},
```

Did you try that?

**Comment by GilbertLasnier** [comment]
Great TIM
You are the king its working Now
Great job Tim
I play with the initial extent now… you are very good…
Thanks a lot I continue my decouverte OF YOUR GREAT WORK!!
