### ISSUE TITLE
You tell about Editor Coming Soon in a table?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#57]
You see in your example a little pencil in the field Action (its for editing or I dream?)
![timedit](https://cloud.githubusercontent.com/assets/6784515/14566194/7c7d6884-02fc-11e6-8d20-138488baf280.jpg)
it s help me to have the edit in the table because the people here like table (Edit in attribute they don t like! to complexes)
also I must stop the silver light services to switch to your template cmv and in silver light we have the possibilities to edit in the table on attribute directly
![timtableedit](https://cloud.githubusercontent.com/assets/6784515/14566559/06625612-02fe-11e6-85e5-74c5aaaec260.JPG)

**Comment by tmcgee** [comment]
@GilbertLasnier Sorry, I have not developed a table editor widget. Another developer @ERS-Long created a [test EditorGrid](https://github.com/ERS-Long/EditorGrid) although I don't know if there is any code to save the edits back to the Feature Service.

**Comment by GilbertLasnier** [comment]
Thanks again for your fast answer  I try the link you give me… Merci
