### ISSUE TITLE
Do you think its possible modifies the Search you make to just create a new layer of the result query?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#58]
Hello TIM
i am still stock with Silver light for that function: Query in silverlight? You are able to select the airports BY ATTRIBUTE to create a new layer...on the map very cool!
EXAMPLE: STATE AOP FILTER, Select Aerodrome by state: here I select EGYPT and in the map content, its appear: STATE AOP FILTER with EGYPT AERODROMES, AND ALSO ON THE MAP I HAVE JUST THE AERODROME OF EGYPT...AND IN THE TABLE OF ATTRIBUTE...
Do you think its possible to do something like that or make that in an other way?
Many thanks again..for all your advised. 
![timquery](https://cloud.githubusercontent.com/assets/6784515/14645645/7ac4f54a-0624-11e6-9f30-26ad1d42dfc3.jpg)

**Comment by tmcgee** [comment]
@GilbertLasnier The ability to easily add new layers to and remove them from the layerControl widget was added to CMV just a few weeks ago. It is not yet available in the released version of CMV. I plan to add that capability to the search/attribute tables widgets when it is available in CMV,

**Comment by GilbertLasnier** [comment]
Perfect its fantastic i am very app with you super app, also I use all the day your select by shape...Do you think its possible to erase the Box or lines the draw tool when you select with the shape and just keep the selection object

**Comment by GilbertLasnier** [comment]
i just go of what you do for the KML, i try tomorrow... its wonderful the dream come true!!
grace a vous!
