### ISSUE TITLE
Do you think it will be possible to just erase the Rectangle

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#59]
Hello Tim
I like your tools so much
You put on your Clear button in the attribute table
Clear All Features,
clear selected feature,
clear grid, 
clear all, 
are you able to add clear selected tool example here: we just clear the Rectangle
or explain to me how to change the select tool with color transparent that will continue to work where I can change that 

![timshape](https://cloud.githubusercontent.com/assets/6784515/14743708/ec0884b2-0870-11e6-8b0f-eec96210eb92.jpg)

**Comment by tmcgee** [comment]
@GilbertLasnier Clearing the selection shape isn't currently supported but a good addition.

**Comment by tmcgee** [comment]
@GilbertLasnier I think you can prevent the source shape from showing with a setting in the configuration. I'll check on that when at my office.

**Comment by tmcgee** [comment]
You can prevent the source shape from showing by using this in the configuration for your specific search:

```
featureOptions: {
    source: false
}
```

This is documented in the [AttributesTable widget](https://github.com/tmcgee/cmv-widgets/tree/master/widgets/AttributesTable#feature-options).

**Comment by GilbertLasnier** [comment]
I don't find where to change  i try many place 
i just find in FeaturesMixin   defaultFeatureOptions: {

```
        // show the features that were the results of the search
        features: true, i put false nothing is selected and the box is still there
```

and in the read me 
i try  search: {
                include: true,
                id: 'search',
                type: 'titlePane',
                path: 'widgets/Search',
                canFloat: true,
                title: 'Search by Field or Shape in ICAO FIR',
                open: false,
                position: 0,
                options: 'config/searchWidget2'
                featureOptions: {
                         source: false
                       }
Nothing ???

**Comment by tmcgee** [comment]
@GilbertLasnier this addition needs to be in the configuration for each specific search. Base on your writing in the last message, those searches are in searchWidget2.js.

**Comment by GilbertLasnier** [comment]
Thanks strange normally your suggestion are always good now I am so poche, I am not able to put one line of code at the good place...
I don't succeed i put everywhere in searchWidget2.js nothing work

**forget it..**.Thanks quand meme!
