### ISSUE TITLE
Attribute Table Not Opening Upon Query (Search Widget)

### ISSUE THREAD

**Issue by JhopStl** [tmcgee/cmv-widgets#62]
I'm having an issue where the attribute table does not pop-up when running a query using the Search widget.  I have the sidebarID set as 'sidebarBottom', (line 467 viewer.js), but I have to manually open it to see the results. Any ideas? I attached AttributesTable.js, Search.js and Viewer.js. 

Thanks!
[ConfigFiles.zip](https://github.com/tmcgee/cmv-widgets/files/265426/ConfigFiles.zip)

**Comment by drusexton** [comment]
@JhopStl did you find a solution to this issue? I am also having the same problem. Every time I execute a query the attributes table does not show up in the bottom pane until you press export, and export the table. It pops up only after the file is downloaded onto the computer. @tmcgee do you know if anyone else has ever had a similar issue?
