### ISSUE TITLE
Share Widget - Cannot find extent when using State Plane Coord Sys.

### ISSUE THREAD

**Issue by JhopStl** [tmcgee/cmv-widgets#63]
Hello,

I'm having issues getting the "include map extent" working when using your share widget.  I have custom basemaps that uses the State Plane coordinate system (wkid 102696 to be exact), so I set this in the widget itself (line 167). useExtent: has to be false or the map won't even load.  I also noticed that line 159 says "//assumes lat/lng", so maybe the problem resides in this chunk of code?  Any suggestions?  

I've attached the file and a screenshot.

Thanks a lot,

Jesse
Share.js - [Share.zip](https://github.com/tmcgee/cmv-widgets/files/285123/Share.zip)

![shareextenterror](https://cloud.githubusercontent.com/assets/16945459/15586677/3e6f8314-234b-11e6-9d45-7363ec42b8cc.JPG)

**Comment by JhopStl** [comment]
I was able to piece together some code that essentially just re-projects the coords via a geometry service. I'm assuming that this is somewhat a 'duh' answer to most, but just throwing it out there. That being said, I can get an extent but it doesn't seem to zoom in to the correct location. I'll create a separate post for this issue if I can't figure it out.  I attached the updated code if anyone needs it.

Thanks,
[Share.zip](https://github.com/tmcgee/cmv-widgets/files/303141/Share.zip)

**Comment by tmcgee** [comment]
Thanks @JhopStl Glad you got something working for you. I composed a suggested fix a few days ago but it isn't here so I guess I didn't hit the "Comment" button when done. Oops.

Quick summary on future direction: I envision using the proj4js JS library to do the reprojection in the browser. That's what we do in the MapInfo and StreetView core CMV widgets and other contributed widgets as well.
