### ISSUE TITLE
Cannot get generated extent parameter to work 

### ISSUE THREAD

**Issue by JhopStl** [tmcgee/cmv-widgets#64]
In regards to a previous issue, I was able to get the "Share" widget to provide me with an extent in the State Plane Coord System by reprojecting via geometry service. However, when attempting to navigate to said extent (copying into browser window), the map just loads as it normally would (i.e. default extent).  I'm not sure if it there is something wrong with the format of the URL string or if it's in the widget itself.  Any tips/help would be much appreciated. 

 **An example URL:** 

 http://map.sccmo.org/Main/gis_dev/viewer/?extent=741984,1067816,792986,1095841

[Share.zip](https://github.com/tmcgee/cmv-widgets/files/303163/Share.zip)

**Comment by tmcgee** [comment]
Just an fyi. The MapServices in this app are not accessible from the outside world so can't see it in action.

**Comment by tmcgee** [comment]
@JhopStl I see that you have the `handeQueryParameters` method commented out. That is the place where it would use the grab the extent from the url. Assuming your map has a spatial reference wkid of 102696, you will need to change the wkid in that method to 102696.

If you map has a spatial reference of 102696 (derived from the basemaps that I cannot see), do you need to project at all using the Geometry Service? In that case wouldn't `map.extent` already be in the proper coordinates?

**Comment by JhopStl** [comment]
Tim, my apologies, I thought the services were exposed.  I'll try to get them up and running.  That makes sense, I will un-comment that out and see how it works.  You are correct, 102696 is the wkid of the basemaps, but yeah strangely, when I try to run the widget without projecting, I get a "cannot read property 'xmin' is undefined" error.

Anyways, I'll try to get the services exposed, mess around with the widget a little more, and provide you with an update.  Thanks for the help.

**Comment by tmcgee** [comment]
I see that map services are exposed now. Still a few errors in the console when the application loads but those are unrelated to the Share widget.

Related to the share widget: I see you have un-commented out the `handQueryParameters` method and added your wkid. You need to add this line back into your widget so the method will be called: https://github.com/tmcgee/cmv-widgets/blob/master/widgets/Share.js#L143

Note to self: the name of that method is misspelled!. ;)

**Comment by JhopStl** [comment]
Tim,

Thanks for checking back. It took me longer then I wanted to get those services exposed, and even then they aren't performing well one bit, plus the tiles are messed up. Anyways, thanks for reminding me to add that method back in, don't know why I removed it instead of commenting it out.  After adding that back in, I tested on a public connection and the extent appears to have worked.  Strangely enough, it only works _sometimes_ behind a firewall/internally.  Even with that, I'm just happy to get some success; I should be able to figure out the rest on my own.

Thanks again for your help!

**Comment by JhopStl** [comment]
Actually, maybe I won't be able to haha.  I've realized that this works every time/perfectly in Firefox and IE, but acts erratically in Chrome (I thought that was the good browser), any ideas on this or tips on where I should start troubleshooting?  The chrome tools don't really provide me with much on this.  

Thanks

**Comment by tmcgee** [comment]
I would not expect it to be the browser specifically. Perhaps it is related to the Chrome network settings related to your firewall/proxy server or the server itself...

**Comment by JhopStl** [comment]
Hmm ok, I'll try to take a look at those tomorrow.  Thanks again!
