### ISSUE TITLE
Cool fullscreen widget.

### ISSUE THREAD

**Issue by ERS-Long** [tmcgee/cmv-widgets#65]
Hi, Tim:

Not an issue, it is an added on.

I added the following so it can hide/show the header also. It has hardcoded div though, not a perfect solution, but it works for me.

Just add the following call in the end of your enterFullScreen function  

```
        //hide the header
        this.turnOffHeader();
```

in the exitFullScreen function

```
        //turn on the header
        this.turnOnHeader();
```

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

```
    turnOffHeader: function()
    {
        dojo.setStyle("borderContainerOuter", {
                "top": "0px"      
        }); 

        this.refreshPane();
    },

    turnOnHeader: function()
    {
        dojo.setStyle("borderContainerOuter", {
                "top": "70px"      
        }); 

        this.refreshPane();
    },    

    refreshPane: function()
    {
        //this will force the map to redraw the client area
        topic.publish('viewer/togglePane', {
            pane: 'bottom',
            show: 'block'
        });

        topic.publish('viewer/togglePane', {
            pane: 'bottom',
            show: 'none'
        });
    },    
```

**Comment by tmcgee** [comment]
@ERS-Long Isn't the positioning of the border container already addressed in the [css](https://github.com/tmcgee/cmv-widgets/blob/master/widgets/FullScreen/css/FullScreen.css#L12)? If not, it should probably be corrected there. The border container may not always have a top of 70px so it is better handled with css than with JavaScript

**Comment by ERS-Long** [comment]
cool, i missed that, but in my google chrome test of your example, it has blank header always there. let me test in IE.

Yes, please see this 
![image](https://cloud.githubusercontent.com/assets/5911272/16592791/f0a11770-42a7-11e6-9076-1ca1339bfdde.png)

**Comment by tmcgee** [comment]
Make sure you have the latest version of that css file. Originally the top/left css was there for only IE. That is what is in the v1.7.0 release. Afterwards I noticed it also occurred occasionally in other browsers (not not Chrome) so implemented that css for all browsers.

**Comment by ERS-Long** [comment]
Not sure about that, Just downloaded your code again, tested locally, it still has that black header for both Chrome and IE.

**Comment by tmcgee** [comment]
That's really odd. I tested this in a lot of browsers. I'll take another look.

**Comment by ERS-Long** [comment]
Worked in FireFox, Just tested. Thanks!
