### ISSUE TITLE
Zoom to feature layer 

### ISSUE THREAD

**Issue by saurabhgis** [tmcgee/cmv-widgets#66]
<div data-dojo-attach-point="featureSelectDom">
                <label data-dojo-attach-point="featureSelectLabel">${i18n.selectFeature}:</label><br/>
                <input type="select" data-dojo-type="dijit/form/FilteringSelect" data-dojo-props="disabled:true,autoComplete:true,'class':'featureSelect'"
                data-dojo-attach-point="featureSelectDijit" data-dojo-attach-event="onChange:onFeatureChange"/>

 <label data-dojo-attach-point="featureSelectLabel">${i18n.selectFeature1}:</label><br/>
                <input type="select" data-dojo-type="dijit/form/FilteringSelect" data-dojo-props="disabled:true,autoComplete:true,'class':'featureSelect'"
                data-dojo-attach-point="featureSelectDijit1" data-dojo-attach-event="onChange:onFeatureChange1"/>

            </div>

**Comment by tmcgee** [comment]
@saurabhgis Nothing here to comment on. Please try again.
