### ISSUE TITLE
code typo error

### ISSUE THREAD

**Issue by thejuskambi** [tmcgee/cmv-widgets#7]
Hi 

It seems there is a code error in ZoomToFeature widget, while setting the renderer for the polygongraphics layer. as shown below the if condition should check for polygonGraphics layer and not polylineGraphics layer.

if (symbols.polygon && this.polylineGraphics) {
polygonSymbol = new SimpleFillSymbol(symbols.polygon);
polygonRenderer = new SimpleRenderer(polygonSymbol);
polygonRenderer.label = 'Search Results (Polygons)';
polygonRenderer.description = 'Search Results (Polygons)';
this.polygonGraphics.setRenderer(polygonRenderer);
}

Please fix the same or let me know, if I can do it.

Warm Regards,
Thejus

**Comment by tmcgee** [comment]
Thanks for pointing this out. It has been fixed
