### ISSUE TITLE
Search configuration help, I need a drop down component instead of text input

### ISSUE THREAD

**Issue by cmccullough2** [tmcgee/cmv-widgets#70]
I have been trying to configure your Search widget. However, I am not doing something correct. I am not sure if I am configuring things out of order??? I am sure it is a simple twist of code.

**Using the Esri Demographics Layer, can you tell me if this is possible? Your Public Safety by Name example is close. I need the placeholder tag to be a drop down instead of a text box. 
http://server.arcgisonline.com/arcgis/rest/services/Demographics/USA_1990-2000_Population_Change/MapServer/1
1. A query must be performed by first choosing a search layer; Fire Stations
2. Search Layer field can one to many fields. These fields use a drop down menu; NAME, TOTPOP_CY, POPGRWCYFY, etc. This is the key component I need. 
3. Individual queries are then passed to render a selection. 
I can do this with the eSearch widget, but it is interfering with other widgets and I need the functionality of your widget. The eSearch widget is giving me the original error message (above) before I make any edits. 
Let me know if this is possible. If not, I can make the eSearch work.

**Comment by tmcgee** [comment]
Can you please clarify what you mean by `Individual queries are then passed to render a selection`.

Is this the kind of result you are looking for?

![image](https://cloud.githubusercontent.com/assets/200780/18395052/9b8fd3d6-7671-11e6-8588-fc1f162b2487.png)

**Comment by cmccullough2** [comment]
This could work.  I would need to have the drop down selection for the fields to be in one dropdown selection.  The attached picture shows the workflow for an user to select an airfield.  It is essentially done in 4 steps:
1. Select a layer - drop down
2. Select a field(s) to complete your selection from a drop down (fields)
3. Text input 
4. click select to complete transaction

![searchcriteria](https://cloud.githubusercontent.com/assets/3169799/18403894/045177f4-76ad-11e6-8ab9-fc6ab4118e59.png)

**Comment by tmcgee** [comment]
Oh. I thought you wanted something complex. ;) The Search widget handles multiple queries for a layer. The `attributeSearches` is an array that can contain any number of searches.

I think this gets what you are after:

``` javascript
{
    name: 'Block Groups',
    expression: '', // additional where expression applied to all queries
    queryParameters: {
        type: 'spatial',
        url: 'http://server.arcgisonline.com/arcgis/rest/services/Demographics/USA_1990-2000_Population_Change/MapServer/1',
        outFields: ['*']
    },
    idProperty: 'OBJECTID',
    title: 'Block Groups',
    topicID: 'blockGroupsQuery',
    attributeSearches: [
        {
            name: 'Select By Name',
            searchFields: [
                {
                    name: 'NAME',
                    label: 'Name',
                    expression: '(NAME = \'[value]\')',
                    unique: true
                }
            ]
        },
        {
            name: 'Select By State',
            searchFields: [
                {
                    name: 'ST_ABBREV',
                    label: 'State',
                    expression: '(ST_ABBREV = \'[value]\')',
                    unique: true
                }
            ]
        },
        {
            name: 'Select By Total Pop',
            searchFields: [
                {
                    name: 'TOTPOP_CY',
                    label: 'Total Pop CY',
                    expression: '(TOTPOP_CY = [value])',
                    unique: true
                }
            ]
        },
        {
            name: 'Select By Rate',
            searchFields: [
                {
                    name: 'RATE_POP',
                    label: 'Rate Pop',
                    expression: '(RATE_POP = [value])',
                    unique: true
                }
            ]
        }
    ],
    gridOptions: {
        sort: [
            {
                attribute: 'NAME',
                descending: 'ASC'
            }
        ]
    }
}
```

![image](https://cloud.githubusercontent.com/assets/200780/18404973/f59e2db0-76a2-11e6-8175-4a7835dc4526.png)

**Comment by cmccullough2** [comment]
This was exactly what I needed.  Thanks again.

**Comment by cmccullough2** [comment]
I am trying to solve a mystery for this.  why is the 'Name:' field type greyed out?  
![image](https://cloud.githubusercontent.com/assets/3169799/22409068/d2632e06-e649-11e6-90c1-51bfedebeb39.png)

**Comment by tmcgee** [comment]
Perhaps you have `unique: true` for that field but the query to retrieve the unique values
1. doesn't return any values (an error?)
or
2. the request times out?

**Comment by cmccullough2** [comment]
I figured it out.
