### ISSUE TITLE
AttributesTable: remove from results

### ISSUE THREAD

**Issue by carrbrpoa** [tmcgee/cmv-widgets#71]
Hey @tmcgee!

Is there a nice way to remove a record from results? Let's say that I did spatial Search and then I want to remove one or some of the resulted records, maybe through a custom column or context menu in hovered line of table. I know how to "inject" custom columns there, my problem is to interact with the table data.

Thanks!

**Comment by carrbrpoa** [comment]
Maybe with `populateGrid` topic publication? Or there is a more polished way?

**Comment by carrbrpoa** [comment]
I digged into AttributesTable stuff and now I'm working to include this option:

![image](https://cloud.githubusercontent.com/assets/10212618/18912790/a438edae-855a-11e6-8c46-d31a060fda85.png)

The idea is to remove graphics from results (highlights and all) and the record from attribute table.

Valid?

**Comment by tmcgee** [comment]
@carrbrpoa Using a menu option is what I would do though not sure that a `Remove` option belongs in the `Clear` menu. Perhaps create a new separate button? @roemhildtg started a discussion about adding custom buttons is in issue #69.

**Comment by carrbrpoa** [comment]
Actually I intend to contribute this feature to AttributeTable, others could benefit from it.
The goal is to clear selected lines of results grid and purple/highlighted/whatever circles around the found features. I could put it in another menu, no problem, just seemed ok to me in `Clear`.

Maybe I could rename to Clear Selected Record(s), which is a mix between Clear Grid and Clear All Features, but handling specific ones.
