### ISSUE TITLE
Search: publish other widget's topic

### ISSUE THREAD

**Issue by carrbrpoa** [tmcgee/cmv-widgets#72]
Hello,

I wish to trigger another widget's event (through `topic.publish`) from `config/searchWidget.js`'s `gridOptions` like this:

``` javascript
gridOptions : {
    columns : [{
            field : 'OSCODIGO',
            label : 'Andamento',
            width : 80,
            formatter : function (value) {
                if (value) {
                    return '<span><i class="fa fa-ban" onclick="someEvent();"><i></span>';
                }
            }
        }, (...)
    ]
}
```

Then, after config's `formatDateTime` declared function, I've created mine:

``` javascript
function someEvent(data) {
    topic.publish('estrategiaOS/analiseEtapa', data);
}
```

The problem is that when I click that `span`, I get

```
Uncaught ReferenceError: someEvent is not defined
```

Is there a way to do it and possibly passing arguments (`data`) to `someEvent`?

Thanks in advance!

**Comment by carrbrpoa** [comment]
Done with `renderCell`!

Changed that `formatter` for:

``` javascript
renderCell : function (object, value, node) {
    on(node, 'click', function () {
        topic.publish('estrategiaOS/analiseEtapa', {
            test : 'hi'
        });
    });
    node.innerHTML = '<i class="fa fa-ban"><i>';
}
```

**Comment by tmcgee** [comment]
Sorry I didn't get to this earlier. There is a more detailed example topic [here](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget-relatedRecords.js#L62)
