### ISSUE TITLE
Search/AttributesTable: QueryTask making use of layerDefinitions 

### ISSUE THREAD

**Issue by carrbrpoa** [tmcgee/cmv-widgets#74]
Related to [this issue](https://github.com/cmv/cmv-app/issues/287#issuecomment-251466157).

Hey @tmcgee,

What do you think about using layer's `layerDefinitions` to increment `queryParameters` (let's say creating a generic `where` clause equals layerDefinitions in `queryParameters`) when using QueryTask and some flag like `considerLayerDefinitions` is on?

See image bellow. We have everything (I guess) in hands there:

![image](https://cloud.githubusercontent.com/assets/10212618/19115696/551557a0-8ae9-11e6-8020-3e3ad5127791.png)

Maybe something like this on cases with `sublayerID` informed:

``` javascript
(...)
}
else if (layer.declaredClass === 'esri.layers.ArcGISDynamicMapServiceLayer') { // Dynamic Layer
    if (qp.sublayerID !== null) {
        url = layer.url + '/' + qp.sublayerID;

        // <New>
        if (layer.layerDefinitions && qp.sublayerID <= layer.layerDefinitions.length) {
            var whereByLayerDef = layer.layerDefinitions[qp.sublayerID];

            if (whereByLayerDef) {
                if (qp.where) {
                    qp.where = '(' + whereByLayerDef + ') AND (' + qp.where + ')';
                } else {
                    qp.where = whereByLayerDef;
                }
            }
        }
        // </New>
    } else if (layer.visibleLayers && layer.visibleLayers.length === 1) {
        url = layer.url + '/' + layer.visibleLayers[0];
    }
}
(...)
```

Or maybe we could consider another piece of code for this modification.

Thanks!

**Comment by tmcgee** [comment]
@carrbrpoa I think the same logic could/should apply to Feature Layers.

With dynamic layers, the sublayerID can be hard-coded in the Map Service so not necessarily sequential. In that case is the sub layer's id still an index into the layerDefinitions? I think that is the case but some testing would be required to verify.

**Comment by carrbrpoa** [comment]
The docs makes me think that yes, but anyway will test ASAP:

![image](https://cloud.githubusercontent.com/assets/10212618/19124078/09c3e4dc-8b08-11e6-8f3c-cd0198746b7e.png)

**Comment by carrbrpoa** [comment]
Hey @tmcgee, confirmed:

I published layer with custom ID = 5, so needed to change my `layerDefinitions` to:

``` javascript
function buildImageParameters(config) {
    var ip = new ImageParameters();

    (...)

    ip['layerDefinitions'][5] = 'ZONAL = \'' + zonalConvertida + '\'';

    (...)

    return ip;
}
```

And didn't need to change the previous proposed code :)

**Comment by tmcgee** [comment]
awesome! A couple of thoughts...
- There might be a problem with this comparison `qp.sublayerID <= layer.layerDefinitions.length` when the sublayerID is explicitly set to some large number like 999. That comparison is probably not needed at all.
- We need similar code to get the layerDefinition for Feature Layer (easy). With that included, this section can be moved outside the if statement towards the bottom of the method:

``` javascript
if (whereByLayerDef) {
    if (qp.where) {
        qp.where = '(' + whereByLayerDef + ') AND (' + qp.where + ')';
    } else {
        qp.where = whereByLayerDef;
    }
}
```
- To not impact existing searches, I think we do need the boolean like `considerLayerDefinitions` with a default of `false`. My suggestion is `includeLayerDefinition`.

Can you put this together in a PR? That would be even more awesome! ;)

**Comment by green3g** [comment]
This is a good idea! Looks like this breaks layers that don't have layerDefinitions. since `layer.layerDefinitions` is `null` and `whereByLayerDef = layer.layerDefinitions[qp.sublayerID];` will throw an error. 

I think we need to do something like this: 

``` javascript
whereByLayerDef = layer.layerDefinitions  ? layer.layerDefinitions[qp.sublayerID] : null;
```
