### ISSUE TITLE
Search Widget: Geometry Engine "invalid arguments"

### ISSUE THREAD

**Issue by green3g** [tmcgee/cmv-widgets#77]
I get an error when doing a combination of selecting/buffering. First, I'm using Firefox Developer 51 2a.

To get this error, I'm doing the following:
1. Select features by rectangle, I'm selecting about 5 parcels
2. Click one of the parcel graphics on the map (this selects one parcel)
3. Enter a buffer distance, I am using 350 feet 
4. Select by selected feature
5. Buffer displays, features are removed from the table, and the error is given. 

![image](https://cloud.githubusercontent.com/assets/5471079/19399710/79b5bd12-9218-11e6-91e7-e3e4d3569279.png)

**Comment by tmcgee** [comment]
@roemhildtg I have tried a couple of different way but cannot duplicate this using the [demo app](https://tmcgee.github.io/cmv-widgets/demo.html?config=search) I am using version 51.0a2 (64-bit) which was just released today. Is that the same version?

**Comment by green3g** [comment]
Nope, I was using a previous version. I'll check the new version on Monday.
Have a good weekend.

**Comment by green3g** [comment]
Looks like its resolved. Not sure what was causing it.

**Comment by green3g** [comment]
![capture](https://cloud.githubusercontent.com/assets/5471079/19869142/09835ed2-9f79-11e6-9bd7-6aa0e2b5a01b.PNG)

Looks like it has started happening again. On firefox beta version (2016-10-31). I am able to replicate this on the demo site.

Detailed Steps:
1. Select features by rectangle
2. Click Search and let the attributes populate the table
3. Click one of the graphics on the map. This turns it a bright blue color.
4. Enter a buffer distance, I am using 350 feet 
5. Click the binoculars icon button 
6. Buffer displays, features are removed from the table, and the error is given. 

![capture](https://cloud.githubusercontent.com/assets/5471079/19869389/2522bbbe-9f7a-11e6-995b-6fd18219e8c4.PNG)

**Comment by tmcgee** [comment]
@roemhildtg I see a slightly different problem with the demo site. It stops at step one selecting features by rectangle. Same error but triggered in a different method. Perhaps it will be resolved in tomorrow's beta update? :wink:

![image](https://cloud.githubusercontent.com/assets/200780/19870069/30fcfd04-9f6c-11e6-8ddf-6d5873d04644.png)

**Comment by green3g** [comment]
Perhaps I should just stick to the stable firefox :wink:

**Comment by tmcgee** [comment]
@roemhildtg should this issue stay open?

**Comment by green3g** [comment]
I thought I had responded to this..sorry. The issue is still happening for me consistently in both Firefox (Dev) and I've also noticed it in IE 11.

It happens in the _QueryTaskMixin on line 373:
`var qParams = lang.clone(this.queryParameters);`

Somewhere along the stack, the geomtery engine receives a null argument. I'll post my widget config for reference:
```javascript
layers: [{
                title: 'Curb Stops',
                name: 'Curb Stop (Tap Cards)',
                topicID: 'curbStop',
                idProperty: 'cid',
                queryParameters: {
                    type: 'spatial',
                    layerID: 'assets',
                    sublayerID: 27
                },
                attributeSearches: [{
                    closable: false,
                    name: 'Search For Curb Stop',
                    searchFields: [{
                        name: 'City ID',
                        label: 'CID',
                        expression: '(cid IN ([value]))',
                        placeholder: 'Enter IDs (comma separated)',
                        required: true,
                        minChars: 1
                    }],
                    title: 'Curb Stop',
                    topicID: 'curb_stop'
                }],
                buttons: [workorderButton, {
                    label: '<i class="fa fa-file-text-o"></i> Tapcard Report',
                    onClick: function () {
                        window.open('/gis/utilities/tap_report/tap/' +
                        this.tab.grid.store.data.map(function (row) {
                            return row['gis.DBO.water_curbstop.cid'];
                        }).join('-'));
                    }
                }]
            }]
```

**Comment by green3g** [comment]
Seems like esri-js bug. Theres some code in lang.clone that does this:

`b = a.constructor ? new a.constructor : {};`

But doesn't pass arguments to the constructor as you can tell. The function throwing the error is in the geometry engine:

```
function a(b) {
    this.Ta = this.Xf = !1;
    this.f = null;
    var e = b;
    2 > e && (e = 2);
    this.f = new Int32Array(e);
    this.size = b
}
```

Since `b` and `e` are undefined, `new Int32Array(e)` throws an error.

**Comment by tmcgee** [comment]
I am seeing this in IE 11 as well.
The error in IE 11 is "Typed array constructor argument is invalid".
From initial testing, if you do not include a buffer distance (distance = 0), it works in IE 11.

**Comment by green3g** [comment]
Yup, that's the error I was getting.

**Comment by tmcgee** [comment]
@roemhildtg I have addressed this in a new commit. Tested in the latest Firefox Developer Edition and IE 1.. Can you please verify that it is fixed for you as well?

**Comment by green3g** [comment]
Yup, that fixed it.
