### ISSUE TITLE
How to put 31,000 elements in the dropdown list of Zoom to feature?

### ISSUE THREAD

**Issue by GilbertLasnier** [tmcgee/cmv-widgets#79]
Hello TIM,  I hope you feel good
I have a lot of question for you?
I make a map of all the TRAFFIC FLOW ROUTE IN THE WORLD and its by city-pair ~31,000 routes...
I use your very good zoom to feature and I try to have more records, I think drop down list is stopping at 1000, 
I try to change on the server... and other place...ext
![capturezoomtofeature5](https://cloud.githubusercontent.com/assets/6784515/20017151/bde38092-a298-11e6-86ed-1f52dd9a560b.JPG)

![listmorethen32000](https://cloud.githubusercontent.com/assets/6784515/20016850/97f95e2a-a297-11e6-992f-be3405db4104.jpg)
![increasenumberofthepuppoplist](https://cloud.githubusercontent.com/assets/6784515/20016947/fc03367a-a297-11e6-86d5-2d045c99030c.JPG)
Do you know if its possible to change the value to have a drop down with all my values...Where?
I use also the Find  from the CMV,  but I will like better the zoom feature that you create easier for user...
![selectionhard](https://cloud.githubusercontent.com/assets/6784515/20017010/3734ebee-a298-11e6-98be-2f7d9d989406.JPG)
Also do you think that its possible to have more fields in the result window of the Find like the dist or the city-pair?  its will be very great!!!
Also when you use Find, its very difficult to select the Route... YOU NEED TO CLICK a lot of time!!!
I try to find where the select tool tolerance in pixel is in CMV? but I don t find!!! to correct the selecting problem.
Many thanks for your great support.
You must try all that to that site:
http://gis.icao.int/GISrouteseg/#/-35.5954/49.9968/4
Try the Find and put just Paris and try to select on the map other Route...
Also try the Zoom Route Name by List go in the middle of the box...
It s that one that I will love, if its work!!!
Do you have an other solution with an other template to just show one of the 31000 routes by selecting in a Dropbox???
Again, Many thanks for your great support.

**Comment by tmcgee** [comment]
@GilbertLasnier 

While 31,000 records will take a VERY long time to download from the server and difficult for the user to navigate and possibly run into memory limits on the browser, the dojo dropdown dijit should be able to handle that many records. However, that service you point to does not return more than 1000 records. I don't remember how or if this can be changed in version 10.02 of ArcGIS Server.  See this query for the 1000 record limit: http://gis.icao.int/ArcGIS/rest/services/RouteSEG/MapServer/3/query?text=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&objectIds=&where=1%3D1&time=&returnCountOnly=false&returnIdsOnly=false&returnGeometry=true&maxAllowableOffset=&outSR=&outFields=&f=html

Clicking (or not clicking) on a graphic on the map is handled directly the Esri JavaScript API not CMV. Clicking on a line graphic can definitely be very tricky. There may be a work-around for this but no easy solution is coming to mind at the moment.

You can add fields to the grid of the Find results. There is an example in the demo files: https://github.com/cmv/cmv-app/blob/master/viewer/js/config/find.js#L30

**Comment by GilbertLasnier** [comment]
Thanks TIM… to your fast answer I try first what you tell me about the You can add fields to the grid of the Find results. There is an example in the demo files: https://github.com/cmv/cmv-app/blob/master/viewer/js/config/find.js#L30

**Comment by GilbertLasnier** [comment]
Hello TIM

I follow your advice and its working… You can add fields to the grid of the Find results. There is an example in the demo files: https://github.com/cmv/cmv-app/blob/master/viewer/js/config/find.js#L30
I have another one about the floatable duck?
DO you think it’s possible to have the do can float at true and open in the viewer at a certain position at the opening??? Like that screen shot?
Also where do you resize the duck in CMV???
Thanks again for your precious collaboration
Gilbert
[cid:image001.png@01D238F0.90AF9BE0]

**Comment by GilbertLasnier** [comment]
At the Opening have that will be great!
I JUST PUT THE PICTURE  that i insert in the precedent email
 ![opening](https://cloud.githubusercontent.com/assets/6784515/20067721/5477d150-a4e4-11e6-9ec8-f6fa7499e329.JPG)
my new link is: http://gis.icao.int/gisroute/#/-52.2507/49.4856/4
Thank again...

**Comment by GilbertLasnier** [comment]
I just go to the find.css to change the size ...I think its not a good Idea...

**Comment by tmcgee** [comment]
@GilbertLasnier Opening a titlePane widget initially in a window is not supported at this time.

**Comment by GilbertLasnier** [comment]
Ok  thanks

**Comment by GilbertLasnier** [comment]
I try to sort with the DIST in KM in the result window, Doesn't work! I don't understood its a number, I just want to sort ascending...How to disable the alphabetic order in the other fields?

**Comment by GilbertLasnier** [comment]
Hello Tim, I change my mind... now I want to sort by the field longCentro to have a sequence of the route in that fields Doesn't work with the sort function! the sort is not in order???
In the best world I must have also the sort on the distKm!!!
The script I use to do that is here from your code: ( I put some code in explanation: //because I don't use)
{
            description: 'Route Segment(Paris-Montreal)or CityPair',
            url: 'http://gis.icao.int/ArcGIS/rest/services/RouteSEG/MapServer',
            layerIds: [ 2],
            searchFields: ['RouteName','marketpair'],
            minChars: 2,
            gridColumns: [
               { field: 'RouteName', label: 'RouteName', width: 80, sortable: false, resizable: false },
               { field: 'longCentro', label: 'Sequence', width: 55, sortable: true, resizable: false },
               { field: 'FIR NAME', label: 'FIRname', width: 60, sortable: false, resizable: false },
               { field: 'Seg dist KM', label: 'DistKM', width: 45 ,sortable: false, resizable: false },
               // { field: 'SORT_VALUE', visible: false, get: function (findResult){
                   // return findResult.RouteName + ' ' + findResult.feature.attributes.NOM_COMP;  //seems better to use attributes[ 'Fcode' ] but fails build.  Attribute names will be aliases and may contain spaces and mixed cases.
               // } }
           ],
           // sort: [
               // {
                   // attribute: 'SORT_VALUE',
                   // descending: false
               // }
           // ],
           prompt: 'pari, PARIS, paris-mont, DFW-SYD, PAR-YMQ',
           selectionMode: 'multiple'

```
    },
```

![sequence1](https://cloud.githubusercontent.com/assets/6784515/20144607/30488d14-a66b-11e6-9147-d1b3b2305d29.JPG)
After I click on the sequence field, the result is not sort!!!!
![seqaftersort](https://cloud.githubusercontent.com/assets/6784515/20144733/88fa5258-a66b-11e6-8716-74b172227ebb.JPG)
Do you thing its must be sort?

**Comment by tmcgee** [comment]
@GilbertLasnier The Find widget is currently hard-coded to sort on the value found - in your case the RouteName or marketpair.

If you would like sorting, I suggest switching to the combination of my search and attributes table widgets. The same "Find" functionality from the Find widget is available in my widgets and you can control the sorting of the results grid.

**Comment by GilbertLasnier** [comment]
Thanks i try that solution

**Comment by GilbertLasnier** [comment]
Thanks for your suggestion i try what you tell me and more 
I use your magnifico example:
http://tmcgee.github.io/cmv-widgets/demo.html?config=queryStringSearch&fips=12115
YOU MUST CLOSE THAT ISSUE
