### ISSUE TITLE
Attribute Table widget( Field Alias)

### ISSUE THREAD

**Issue by saurabhgis** [tmcgee/cmv-widgets#82]
Hi,
How to configure layerwise field alias name in Attribute Table widget.
Please provide help if anyone implement this.

**Comment by tmcgee** [comment]
@saurabhgis you can set the label for the dgrid column. Here's an [example](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L96) in this repo. You can also check out the dgrid [documentation](https://github.com/SitePen/dgrid/blob/v1.1.0/doc/components/core-components/Grid.md) for more info.
