### ISSUE TITLE
Open attribute table when map loads

### ISSUE THREAD

**Issue by wrightgd** [tmcgee/cmv-widgets#9]
I would like my attribute table to be open when the map loads and display a list of the features included in the operational layer I have already added to my map.

My first approach to this was to include this operational layer with a "1=1" query as a table to the list of tables to be loaded when the widget is first instantiated.  This did accomplish the desired functionality of opening the table when the map loads, but duplicate graphics were appearing on the map.  This is a points layer, so the first set of graphics are symbolized as programmed into the MapService.  The second set of graphics are the purple round marker symbols--default for search results.

I next tried changing the query type from 'spatial' to 'table' thinking that this would populate the table only, but not add a duplicate layer to the map.  Still no luck.

Is this functionality currently supported?  Thanks for your help!

**Comment by tmcgee** [comment]
@wrightgd If you want no interaction with the map from the table, you can add this to the table's options:

``` javascript
featureOptions: {
    features: false
}
```

If you want to be able to select and zoom to the features from the table but not see the query graphics on the map, you can change the opacity of the feature symbols to hide them:

``` javascript
symbolOptions: {
    features: {
        point: {
            color: [200, 0, 200, 0], // the last value in the array is the opacity
            outline: {
                width: 0
            }
        },
    }
}
```

**Comment by tmcgee** [comment]
I noticed that the first option I mentioned was omitted from the widget's documentation. I have corrected this.

**Comment by wrightgd** [comment]
Thanks! This gets me part of the way there.  I have also implemented the search widget.  Ideally, when someone searches, either: 
a) purple marker symbols would be added on top of the normal features to illustrate which features match the search result, or 
b) the normal features would be filtered for only those matching the search criteria (with no purple markers being added on top).

Under both of these options, the table should also update to match the searched criteria.  Is this possible?

**Comment by tmcgee** [comment]
@wrightgd If I am understanding you correctly, option 'a' is how the widgets work today. Each new search request updates the marker symbols and the contents of the table. If that is not happening for you, please describe further.

Option 'b' for filtering the features in a layer is not something available directly within the AttributesTable or Search widgets. You can likely accomplish this additional functionality by applying the same search criteria to a layerDefinition query on the layer. The approach is slightly different for [dynamic layers](https://developers.arcgis.com/javascript/jsapi/arcgisdynamicmapservicelayer-amd.html#setlayerdefinitions) versus [feature layers](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#setdefinitionexpression). That could be done as an enhancement to the AttributesTable widget or the Search widget or possibly a completely separate widget of your own design. If you do get this layer filter working with any of these approaches, please consider contributing your efforts back as a Pull Request.

**Comment by wrightgd** [comment]
@tmcgee Under option a), when the user initially opens the map, the table would be displayed with the full list of features, but no purple markers would be displayed on the map.  Entering a search criteria and clicking search in the Search widget would both filter the table and display marker symbols.

I agree that this is similar to existing operation, but the difference is what happens when the map is initially opened.  I have the "1=1" query implemented currently.  The result of this is that when the map is opened, the table is populated and the purple marker symbols are displayed.

The overall goal is to have the table (and not the map) default to a "1=1" query when no search is specified, then be filtered with purple markers displayed on the map when a search query is entered.

Does all this make sense?

**Comment by tmcgee** [comment]
Ok. so you want each search to update the existing table. That can be accomplished If you use the same topicID for your initial [table config](https://github.com/tmcgee/cmv-widgets/blob/master/config/table.js#L69) and in your [search config](https://github.com/tmcgee/cmv-widgets/blob/master/config/searchWidget.js#L50).

Above I gave an example of how you could hide the marker symbols in the initial table config, you could do the reverse in the search config to show the marker symbols when filtered.

**Comment by wrightgd** [comment]
@tmcgee Thank you--this is helpful.  Will try out a couple of different things and look into a PR when I get something working.
